yudility/baekjoon-algorithm-study

week01/BOJ_18258/큐2_박유진.java
- 알고리즘 종류: 큐, 연결리스트
- 알고리즘 개념 간단 설명
- 큐:  FIFO(First In First Out) 구조의 자료 구조로, 들어온 순서대로 나간다.
- 연결리스트: 노드가 서로 연결되어있어 삽입/삭제가 빠른 자료구조이다.
```java
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
```
- java의 경우 Scanner 와 System.out.println()을 사용할 경우 시간 초과가 뜨는 문제가 있습니다. 따라서 비교적 입출력이 빠른 BufferReader, BufferWriter를 사용해주었습니다. [참고자료](https://velog.io/@myhuon/%EB%B0%B1%EC%A4%80-%EC%8B%9C%EA%B0%84%EC%B4%88%EA%B3%BC-%ED%95%B4%EA%B2%B0)
```java
LinkedList<Integer> list = new LinkedList<>();
```
- 배열은 삽입/삭제가 느리기 때문에 연결리스트를 이용하여 구현하였습니다. 
```java
int n = Integer.parseInt(br.readLine());
for (int i = 0; i < n; i++) {
String command = st.nextToken();
switch (command) …
```
=> 큐2 / 실버4 / 34분 / X

week01/BOJ_18258/큐2_김준우.java
- 알고리즘 종류: Queue, LinkedList 자료구조 사용
- 알고리즘 설명: 큐는 FIFO(First In First Out) 특성을 가지고 있으며, 자바에서는 Queue 인터페이스를 제공합니다. 다양한 구현체 중에서, 이 문제에서는 LinkedList가 가장 적합하다고 판단하여 선택했습니다.
- 각 명령어에 따른 동작을 구현하기 위해 switch문을 사용했습니다.
- 명령어에 따른 출력을 좀 더 깔끔하게 처리하기 위해 삼항 연산자를 활용하여 출력 코드를 작성했습니다.
=> 큐2 / 실버4 / 25분/ O

week01/BOJ_1158/요세푸스문제_김준우.java
- 알고리즘 종류: Queue, LinkedList 자료구조 사용
- 알고리즘 설명: 이번 문제는 큐를 사용해서 해결하였습니다.
- 총 인원이 주어지고 제거되는 순서가 주어집니다. 제거되는 순서에 해당하지 않는 사람들은 큐에 다시 담기고, 제거되는 순서에 해당하는 사람은 제거됩니다.
- 출력을 위해 ArrayList를 사용하였습니다.
=> 요세푸스문제/실버4/15분/O

week01/BOJ_9012/괄호_연예림.java
- 알고리즘 종류: 스택
스택은 FILO 구조로 선입후출로 구성된 자료구조입니다.
Stack 이라는 컬렉션도 있긴 한데 저는 deque를 사용하여 구현하였습니다. 
```
Deque<Character> stack = new LinkedList<>();
char[] input = br.readLine().toCharArray();
boolean flag = true;
```
flag라는 체크 변수를 사용했습니다.
좀 더 효율적인 방법이나 개선할 부분이 있다면 알려주시면 감사하겠습니다~!
=> 괄호 / 실버4 / 20분 / O

week01/BOJ_9012/괄호_김준우.java
- 알고리즘 종류: 스택 자료구조
- 알고리즘 개념 간단 설명: 스택의 LIFO 특성을 활용해서 올바른 괄호 문자열 판별
- 괄호 문자열을 Character 배열로 만들어서 괄호를 하나씩 확인 후 '(' 괄호이면 stack에 push 하고 ')'이면 stack을 확인하고 만약 '(' 괄호가 있다면 pop을 하도록 하였습니다.
=> 괄호/실버4/20분/O

week01/BOJ_1158/요세푸스문제_연예림.java
- 알고리즘 종류: 큐
이것도 큐를 사용하는 문제였습니다. 문제 풀이 부분은 괜찮았는데,
출력하는 부분에서 어떤식으로 출력할 지 고민했었습니다. 결국 stream을 사용해서 출력하는 방식을 찾아서 적용해보았습니다.
리스트나 collection을 String으로 변환하고 앞, 뒤 출력 문자까지 파라미터로 넣어줄 수 있더라구요.
```
String str = result.stream()
.map(String::valueOf)
.collect(Collectors.joining(", ", "<", ">"));
System.out.println(str);
```
다른 분들은 어떤 식으로 출력하셨는지 궁금하네요~
=> 요세푸스문제 / 실버4 / 40분 / X

week01/BOJ_1874/스택수열_민기.java
- 알고리즘 종류: 스택을 이용하여 구현
- 알고리즘 개념 간단 설명: 스택의 LIFO특성을 활용하여 수열을 만드는 과정을 구현. 오름차순으로 push하고 필요할 때 pop하는 방식으로 목표 수열 생성 시도했습니다.
1. BufferedReader를 사용하여 입력값 n을 받음
2. current 변수로 스택에 넣을 다음 숫자 관리
3. 각 target 숫자에 대해 다음의 작업을 반복:
- current부터 target까지 스택에 push하며 '+' 기록
- stack의 top이 target과 같으면 pop하고 '-' 기록
- 다르면 수열 생성 불가능으로 판단하고 'NO' 출력
- 더 최적화할 수 있는 부분이 있다면 조언 부탁드립니다
- 결국 실제로 target부분에 대해 구현에 실패하여 어떤식으로 먼저 접근을 해야될지 피드백 부탁드리겠습니다
=> 스택수열/ 실버2 / 35분 / X

week01/BOJ_10866/덱_박유진.java, week01/BOJ_18258/큐2_박유진.java
- 알고리즘 종류: 덱(Deque)
- 알고리즘 개념 간단 설명: 큐와 유사하지만 앞뒤 모두 넣고 빼는게 가능한 자료구조
- LinkedList를 이용하여 덱을 구현하였습니다.
- switch-case 문과 삼항 연산자를 사용하여 구현하였습니다.
피드백 환영합니다!
=> 덱 / 실버4 / 22분 / O

week01/BOJ_1158/요세푸스문제_박유진.java, week01/BOJ_18258/큐2_박유진.java
알고리즘 종류:  원형 큐
알고리즘 개념 간단 설명: 원형으로 이루어진 큐로, 헤드와 리어가 연결된 자료구조이다. 
원형큐 처럼 생각해서 다시 넣는 형식으로 생각해보았습니다.
코드 피드백 환영합니다!
=> 요세푸스문제 / 실버4 / 42분 / O

week01/BOJ_10866/덱_김준우.java
- 알고리즘 종류: Deque 자료구조
- 알고리즘 개념 간단 설명: Deque는 앞에 데이터를 추가 제거, 뒤에서 데이터를 추가 제거가 가능한 자료구조이다.
- Java에서 제공하는 Deque를 사용했으며 구현체로는 ArrayDeque를 사용했습니다.
- 각 명령어에 해당하는 메서드를 switch-case 문으로 구현했으며 출력은 삼항연산자를 사용했습니다.
=> 덱/실버4/15분/O

week01/BOJ_1874/스택수열_김준우.java
- 알고리즘 종류: 스택 자료구조
- 알고리즘 개념 간단 설명: 스택은 LIFO 특성을 갖는 자료구조이다.
- 먼저 스택 peek를 가리키는 cur 이라는 변수를 선언했고, cur 보다 입력으로 받은 숫자가 크다면 차이만큼 스택에 숫자를 담고 pop을 하였습니다. 그리고 만약 cur 보다 입력으로 받은 숫자가 작다면 NO를 출력하도록 했습니다.
=> 스택수열/실버2/30분/X

week01/BOJ_1874/스택수열_연예림.java
- 알고리즘 종류: Stack
- 알고리즘 개념 간단 설명: FILO가 특징인 자료구조입니다.
다음 출력 해야하는 값이 stack의 peek값보다 작거나 같으면 계속 pop 하는 방식을 사용했습니다.
처음에 `(int) nums.get(next))` 를 형변환을 하지 않고 연산자로 그대로 비교해서 한 번 틀렸었습니다.
```java
boolean flag = true;
int next = 0;
for (int i = 1; i <= n; i++) { // 카운트
stack.offer(i);
sb.append("+").append("\n");
// nums 값이 stack의 peek값보다 작거나 같으면 계속 pop
while (!stack.isEmpty() && stack.peekLast() >= (int) nums.get(next)) {
sb.append("-").append("\n");
if (stack.pollLast() != (int) nums.get(next)) {
flag = false;
break;
}
next++;
}
if (!flag) {
break;
}
}
```
=> 스택수열 / 실버2 / 30분 / O

week01/BOJ_10866/덱_연예림.java
- 알고리즘 종류: 덱
- 알고리즘 개념 간단 설명: Deque는 Double-ended Queue로 양 쪽 방향에서 삽입과 삭제를 할 수 있는 자료구조입니다.
큐2 문제와 같이 토큰라이저로 공백으로 나눠 받고  switch 문으로 처리했습니다.
:)
=> 덱 / 실버4 / 20분 / O

week01/BOJ_18258/큐2_민기.java
- **알고리즘 종류**: Queue  
- `ArrayDeque`를 사용하여 **큐 명령(push, pop, size, empty, front, back)** 을 `O(1)` 시간으로 수행합니다.  
- 양쪽에서의 삽입/삭제가 빠르게 처리되도록 구현하였습니다.
1. **입력 처리**
- `BufferedReader`를 사용해 명령의 총 개수 `n`을 입력받습니다.
2. **큐 자료구조 선택**
- `ArrayDeque`를 이용하여 큐를 구현합니다.  
- `ArrayDeque`는 **양쪽에서의 삽입과 삭제가 빠르며**, 명령의 수가 많을 경우에도 **효율적**입니다.
3. **명령 처리**
- 입력된 각 명령에 따라 조건문으로 분기하여 처리합니다:
- `push X`: 문자열을 분리해 `X`를 정수로 변환한 후, `offer()` 메서드를 사용해 큐에 추가합니다.
- `pop`: 큐가 비었으면 `-1`을 출력, 아니면 `poll()`을 사용해 **큐의 앞 요소를 제거**하고 출력합니다.
- `size`: 큐의 현재 크기를 출력합니다.
- `empty`: 큐가 비어 있으면 `1`, 아니면 `0`을 출력합니다.
- `front`: 큐가 비었으면 `-1`, 아니면 `peekFirst()`를 사용해 **가장 앞의 원소**를 출력합니다.
- `back`: 큐가 비었으면 `-1`, 아니면 `peekLast()`를 사용해 **가장 뒤의 원소**를 출력합니다.
4. **출력 최적화**
- `StringBuilder`를 사용해 **각 출력 결과를 누적**하고, 마지막에 한 번에 …
=> 큐2/실버4/28분/O

week01/BOJ_10866/덱_민기.java
- **알고리즘 종류**: queue
ArrayDeque를 이용하여 양쪽 끝에서의 삽입 및 삭제를 O(1) 시간 내에 처리합니다.  
입력으로 주어지는 다양한 덱 명령(push_front, push_back, pop_front, pop_back, size, empty, front, back)을 분기하여 처리합니다.
1. **입력 처리**:  
- BufferedReader를 사용하여 명령의 개수 N 및 각 명령어를 빠르게 입력받습니다.
2. **자료구조 선택**:  
- ArrayDeque<Integer>를 이용해 덱(Deque)을 구현합니다.
- StringBuilder를 사용하여 출력 결과를 누적해, 마지막에 한번에 출력함으로써 입출력 효율을 높입니다.
3. **명령어 처리**:  
- **push_front X**: `offerFirst()`를 사용하여 정수 X를 덱의 앞쪽에 추가합니다.  
- **push_back X**: `offerLast()`를 사용하여 정수 X를 덱의 뒤쪽에 추가합니다.  
- **pop_front**: 덱이 비어있으면 "-1", 그렇지 않으면 `pollFirst()`로 제거한 값을 출력합니다.  
- **pop_back**: 덱이 비어있으면 "-1", 그렇지 않으면 `pollLast()`로 제거한 값을 출력합니다.  
- **size**: 덱에 저장된 정수의 개수를 출력합니다.  
- **empty**: 덱이 비어있으면 "1", 그렇지 않으면 "0"을 출력합니다.  
- **front**: 덱의 앞쪽 원소를 조회하며, 비어있을 경우 …
=> 덱/ 실버4 / 20분 / O

baekjoon-algorithm-study.iml, week01/BOJ_10866/덱_한성지.java, week01/BOJ_1158/요세푸스문제_한성지.java, week01/BOJ_18258/큐2_한성지.java, week01/BOJ_1874/스택수열_한성지.java, week01/BOJ_9012/괄호_한성지.java
- 알고리즘 종류: 스택
1. 스택에 타겟까지 숫자 push
2. 스택이 타겟을 가지고 있고, peek가 타겟일 경우 pop
3. 스택이 타겟을 가지고 있으나, peek가 타겟이 아닐 경우 NO 출력
4. 반복문이 끝나도 스택이 비어있지 않다면 NO 출력
=> 스택수열 / 실버2 / 65분 / O

baekjoon-algorithm-study.iml, week01/BOJ_18258/큐2_한성지.java
- 알고리즘 종류:  Queue
- 알고리즘 개념 간단 설명: 가장 먼저 들어온 데이터가 가장 먼저 나가는 자료구조 (FIFO)
1. BufferedReader를 통해 입력 받음
2. Queue 인터페이스를 이용해 queue 생성
3. switch문을 통해 입력받은 명령 구분 및 구현
4. StringBuilder를 이용해 출력 (System.out.println()으로 출력 시 출력 시간 초과 문제 발생)
=> 큐2 / 실버4 / 50분 / O

baekjoon-algorithm-study.iml, week01/BOJ_10866/덱_한성지.java, week01/BOJ_1158/요세푸스문제_한성지.java, week01/BOJ_18258/큐2_한성지.java
- 알고리즘 종류: 큐
1. 큐에 1 ~ n 숫자 채우기
2. queue가 빌 때까지 queue의 1~k-1번째 사람을 뒤로 보내고, k번째 사람을 queue에서 제거와 동시에 StringBuilder에 추가
3. StringBuilder 출력
=> 요세푸스문제 / 실버4 / 30분 / X

baekjoon-algorithm-study.iml, week01/BOJ_10866/덱_한성지.java, week01/BOJ_1158/요세푸스문제_한성지.java, week01/BOJ_18258/큐2_한성지.java, week01/BOJ_1874/스택수열_한성지.java, week01/BOJ_9012/괄호_한성지.java
- 알고리즘 종류: 스택
- 알고리즘 개념 간단 설명: 데이터를 차곡차곡 쌓아 올린 형태의 자료구조 (LIFO, Last In First Out)
1. 중첩반복문 사용
2. 첫번째 반복문은 테스트 개수(t)만큼 반복
3. 받은 문자열을 split을 통해 한 단어씩 잘라 배열로 저장
4. 배열 길이가 홀수인 경우 NO 출력
5. 두번째 반복문은 3번에서 만든 문자열 길이만큼 반복
6. "("일 경우 stack에 push, ")"일 경우 pop
7. 두번째 반복문을 돌다가 ")"일 때 stack이 비는 경우 NO 출력
8. 두번째 반복문 끝난 후 stack이 비지 않은 경우 NO, 비는 경우 YES 출력
=> 괄호 / 실버4 / 40분 / O

week02/BOJ_2075/N번째큰수_한성지.java
- 알고리즘 종류: 최대힙
1. 최대힙 생성
2. n*n개의 숫자를 최대힙에 넣음
3. 최대힙에서 n-1번째 숫자까지 제거 후 root 출력
=> N번째큰수 / 실버3 / 30분 / O

week02/BOJ_2075/N번째큰수_연예림.java
- 알고리즘 종류: 우선순위큐
우선순위 큐는 기본적으로 큐의 특징인 FIFO 특징을 가지지만, 높은 우선순위의 요소를 먼저 꺼내어 처리한다. 
Comparable Interface를 통해 비교 기준을 정할 수 있다. 
내부 구조가 힙으로 구성되어 시간복잡도가 `O(NLogN)` 이다.
참고: <a href="https://velog.io/@gillog/Java-Priority-Queue%EC%9A%B0%EC%84%A0-%EC%88%9C%EC%9C%84-%ED%81%90">[Java] Priority Queue(우선 순위 큐)</a>
위로 갈수록 큰 값이니까 행을 기준으로 정렬만 하면 된다고 생각했는데, 시간초과가 날 것 같더라구요. 우선순위 힙은 생각하지 못했습니다. 자료를 참조하여 사용하였습니다.
```java
PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());
```
`Collections.reverseOrder()`를 사용하여 큰 값을 우선순위로 하고 요소값을 꺼냈습니다.
-> 지금 생각해보면 문제에서 아랫값이 윗 값보다 무조건 크다는 말이 부모자식 간의 정렬이 보장된 힙에 대한 힌트였던 것 같습니다.
다른 분들은 어떤 식으로 풀으셨는지 궁금하네요
=> N번째큰수 / 실버3 / 40분 / X

week02/BOJ_2800/괄호제거_박유진.java
- 30분 고민해보았으나 풀이가 생각나지 않아 해설 참고하였음
- 알고리즘 종류: 스택, dfs
>  DFS(Depth First Search, 깊이 우선 탐색)
> 트리를 순회한다고 생각하였을때, 루트에서 시작하여 리프 노드 까지 들어가서 다시 나오는 형태로 탐색하는 알고리즘.  하나의 경로를 끝까지 탐색한 후 다음 경로로 넘어가는 알고리즘으로 주로 스택이나 재귀를 사용해 구현하며, 한 노드에서 시작해서 다음 분기(branch)로 넘어가기 전에 해당 분기를 완벽하게 탐색하는 방식이다.
- 추후 추가하겠습니다. 
- 피드백, 의견 환영합니다!
=> 괄호제거 / 골드4 / 55분 / X

week02/BOJ_2075/N번째큰수_박유진.java
- 알고리즘 종류: 우선순위 큐, 힙
> **우선순위 큐(PriorityQueue)** 
FIFO 형태의 큐에서 우선순위를 적용한 것으로, 기본적으로 선입선출을 하나, 우선순위가 높은 것 부터 출력한다.
> **힙(Heap)**
데이터 삽입 삭제에 모두 O(log n)의 시간 복잡도를 가지는 자료구조로 완전 이진 트리 형태이다. 부모의 값은 항상 자식(들)의 값보다 크거나(최대 힙), 작아야(최소 힙)하는 규칙이 있다. 따라서 루트 노드에는 항상 데이터들 중 가장 큰 값(혹은 가장 작은 값)이 저장되어 있기 때문에, 최댓값(혹은 최솟값)을 O(1) 안에 찾을 수 있다.
```java
// PriorityQueue 는 기본적으로 오름차순 정렬이므로 
// Collections.reverseOrder()을 사용하여 내림차순 으로 변경
PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());
```
- 피드백, 의견 환영합니다!
=> n번째 큰 수 / 실버3 / 19분 / O

week02/BOJ_1620/나는야포켓몬마스터이다솜_박유진.java
- 알고리즘 종류: 맵(Map)
- 알고리즘 개념 간단 설명: key-value쌍으로 이루어진 자료 구조로, 검색이 빠르다.
```java
// 도감번호 -> 이름 변환을 위한 Map
Map<Integer, String> numName = new HashMap<>();  
//이름 -> 도감번호 변환을 위한 Map
Map<String, Integer> nameNum = new HashMap<>();
```
```java
while (m-- > 0) {
String input = br.readLine();
// 숫자인지 문자인지 판별함
boolean isNum = Character.isDigit(input.charAt(0));
// 숫자(도감번호)라면 numName 에서 value 가져옴
if (isNum) {
sb.append(numName.get(Integer.parseInt(input))).append("\n");
// 문자(이름)라면 nameNum 에서 value 가져옴
} else {
sb.append(nameNum.get(input)).append("\n");
}
}
```
- 피드백, 의견 환영합니다!
=> 나는야포켓몬마스터이다솜 / 실버4 / 23분 / O

week01/BOJ_1874/스택수열_박유진.java
- 알고리즘 종류: 스택
``` java
//후위 연산자 사용 - 준우님 코드 참고
while (n-- > 0) {
// 입력 받는 수열을 한 줄 씩 읽는다.
int a = Integer.parseInt(br.readLine()); 
// 스텍이 비어있거나, 스택의 top의 값이 a보다 작다면,  a가 될 때 까지 i 값을 증가시키며 Push 
if(stack.isEmpty() || stack.peek() < a) {
while(i<=a){
stack.push(i++);
builder.append("+\n");
}
}
// 스택의 top의 값이 a와 같다면, pop
if (stack.peek().equals(a)) {
stack.pop();
builder.append("-\n");
// 그 외의 경우( a가 top보다 큰 경우)라면 스택을 사용하여 해당 수열을 만들 수 없다.
} else {
flag = false;
break;
}
}
```
- 피드백, 의견 환영합니다!
=> 스택수열 / 실버2 / 42분 / X

week02/BOJ_2075/N번째큰수_이유빈.java
- 알고리즘 종류: 우선순위 큐
**큐**란 FIFO 형식의 자료구조인데 **우선순위 큐**는 단순히 먼저 들어온 데이터가 아니라 우선순위가 높은 데이터가 먼저 나가는 자료구조이다. 
이는 **힙**이라는 완전이진트리 형태로 구현된다.
1. 우선순위 큐 생성하여 들어오는 순서대로 입력
2. n-1개만큼 삭제
3. n번째 수 출력
n번째 수를 출력하는 더 좋은 방법이 있을까요?
=> N번째큰수 / 실버3 / 27분 / O

week02/BOJ_1620/나는야포켓몬마스터이다솜_연예림.java
- 알고리즘 종류: map과 리스트
- 알고리즘 개념 간단 설명: map은 키와 value 형태로 저장되는 자료구조입니다. List는 순차적으로 저장되는 자료구조입니다.
String과 int로 모두 탐색이 편하도록 map과 list를 하나씩 사용했는데,
사실 인덱스로 접근할 필요없이 둘 다 map으로 사용하는게 나을 것 같습니다.
```java
HashMap<String, Integer> map = new HashMap<>();
List<String> list = new ArrayList<>();
```
처음에는 string을 int로 변환 가능한지 체크하는 메서드가 생각이 안나서 그냥 예외처리로 넘겼습니다 ㅎㅎ
```java
try {
int num = Integer.parseInt(question);
sb.append(list.get(num - 1)).append("\n");
} catch (NumberFormatException e) {
sb.append(map.get(question)).append("\n");
}
```
관련 메서드를 찾아서 다시 적용했었습니다~
```java
for (int i = 0; i < m; i++) {
String question = br.readLine();
char[] charList = question.toCharArray();
if (Character.isDigit(charList[0])) {
int num = Integer.parseInt(question);
sb.append(list.get(num - 1)).append("\n");
} else { …
```
=> 나는야포켓몬마스터이다솜 / 실버4 / 20분 / O

week02/BOJ_11279/최대힙_연예림.java
- 알고리즘 종류: 최대힙
**힙** : 부모 자식 간의 정렬을 보장하는 자료구조이다. 단 형제 간의 정렬은 보장하지 않는다.
**최대힙**: 루트노드가 최댓값인 힙이다. 트리 노드의 가장 끝 위치에 데이터를 삽입하고 부모노드와  key값을 비교하여 클 경우 부모 노드와 자리를 교체한다.
자바에서의 힙은 우선순위큐를 통해 구현할 수 있다. 우선순위큐가 힙의 구조로 이루어져있기 때문이다.
`PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());`
위 코드를 통해 최대힙으로 사용하였다.
실버 4가 더 헷갈렸던 것 같네요 ㅎㅎ
=> 최대힙 / 실버2 / 10분 / O

week02/BOJ_2800/괄호제거_민기.java
- **알고리즘 종류**: DFS, 백트래킹, 스택 활용
주어진 수식에서 괄호 쌍의 위치를 스택을 이용해 찾은 후, DFS와 백트래킹을 통해 괄호를 제거하는 모든 경우의 수를 탐색합니다.  
제거된 괄호 쌍 조합으로 생성된 수식을 TreeSet에 저장하여 중복을 제거하고 사전순으로 정렬합니다.
---
1. **입력 처리와 괄호 쌍 추출**:  
- `BufferedReader`를 통해 수식을 입력받고, 스택을 사용해 괄호의 인덱스 쌍을 `pairs` 리스트에 저장합니다.
2. **DFS와 백트래킹을 이용한 괄호 제거**:  
- DFS를 통해 각 괄호 쌍에 대해 제거 여부를 결정하는 `boolean[] removed` 배열을 업데이트하며 모든 조합을 탐색합니다.
- 모든 조합 중, 아무 괄호도 제거하지 않은 경우를 제외하고, 제거할 괄호 인덱스를 기준으로 새로운 수식을 생성합니다.
3. **결과 처리**:  
- 생성된 수식들은 `TreeSet`에 저장되어 사전순 정렬된 후 출력됩니다.
---
-
=> 괄호제거 / 골드4 / 40분 / X

week02/BOJ_11279/최대힙_김준우.java
- 알고리즘 종류: PriorityQueue 자료구조를 이용한 maxHeap 구현
- 자바 PriorityQueue는 힙으로 구현되어 있습니다 <-> TreeSet은 완전탐색트리로 구현
- min-힙은 다음과 같은 특성을 보입니다.
1. 모양 성질 
- 마지막 레벨을 제외한 각 레벨의 노드는 모두 채워져 있어야 한다.
- 마지막 레벨에서는 노드들이 왼쪽부터 채워져야 한다.
2. min-heap 성질
- 루트 노드에는 가장 작은 값이 저장된다.
- 루트 노드를 제외한 모든 노드에 저장된 값은 자신의 부모 노드의 값보다 작으면 안된다.
3. [주의] 실제 데이터 값은 리스트에 저장되어 있고 리스트의 값이 표현하는 이진트리가 모양 성질을 만족한다는 의미이다.
- PriorityQueue 자료 구조를 사용해서 max-heap을 구현했습니다. 그리고 입력으로 0이 주어질 때 최대값이 출력되도록 했습니다.
- 궁금한 점이 있다면 언제든 물어봐주세요!
=> 최대힙/실버2/15분/O

week02/BOJ_1620/나는야포켓몬마스터이다솜_김준우.java
- 알고리즘 종류: Map 자료구조
- 알고리즘 개념 간단 설명: Map은 key와 value를 갖는 자료구조입니다.
- 입력으로 자연수인지 판별하는 isInteger 메서드를 만들어서 사용했습니다. 처음에 숫자가 주어지면 해당하는 값을 map.entrySet()을 통해서 일치하는 value를 갖는 key를 출력하려고 했으나 시간 초과가 나서 문자열을 key로 사용하는 map과 Integer를 key로 사용하는 map 총 2개의 자료구조를 사용해서 문제를 해결했습니다.
- 궁금하신 점 있다면 언제든  물어봐주세요!
=> 나는야포켓몬마스터이다솜/실버4/30분/X

week02/BOJ_2800/괄호제거_김준우.java
- **알고리즘 종류:** Stack, TreeSet 자료구조, 비트마스킹  
- **비트 마스킹**은 이번 알고리즘 스터디를 통해 처음 알게 되었습니다.  
간단히 설명하자면 **이진수 특성을 활용한 기법**이며, 이를 통해 **배열의 부분집합을 손쉽게 구할 수 있는 장점**이 있습니다.  
- 자세한 설명이 잘 되어 있는 블로그를 참고하시면 좋을 것 같습니다.  
- 🔗 [[참고 블로그](https://doinitright.tistory.com/90)](https://doinitright.tistory.com/90)  
---
```java
public static ArrayList<ArrayList<Integer>> generateSubsets(int[] arr) {
int n = arr.length;
ArrayList<ArrayList<Integer>> totalSubset = new ArrayList<>();
for (int i = 1; i < (1 << n); i++) {  // 1부터 2^n - 1까지 반복
ArrayList<Integer> subset = new ArrayList<>();  // 부분집합 저장 리스트
// i의 j번째 비트가 1이면 arr[j]를 부분집합에 추가
for (int j = 0; j < n; j++) {
if ((i & (1 << j)) > 0) {  // j번째 비트가 1이면 해당 원소 포함
subset.add(arr[j]);
}
}
totalSubset.add(subset);
}
return totalSubset;
}
```
---
- **TreeSet …
=> 괄호 제거/골드4/45분/X

week02/BOJ_2075/N번째큰수_김준우.java
- 알고리즘 종류: PriorityQueue 자료구조
- 알고리즘 개념 간단 설명: PriorityQueue 자료구조는 정의된 우선순위를 보장하는 자료구조입니다. 
- 최대힙 문제에서 PriorityQueue를 사용했던 기억으로 이번 문제에도 같은 자료구조를 사용해서 코드를 구현해보았습니다.
- 문제에서 나온 데이터의 모양이 Tree와 비슷해보여서 max-heap을 사용했습니다.
- 같은 데이터가 없다는 문장을 근거로 처음에는 TreeSet도 고민을 해보았으나 해당 자료구조를 사용하면 메모리 초과가 발생했고 인터넷에서 알아본 결과 PriorityQueue는 heap을 사용하고 TreeSet은 이진탐색트리를 사용하는데, heap이 다른 자료구조보다 메모리 사용이 적다는 것을 알게 되었습니다.
- 궁금하신 점이 있다면 언제든 물어보셔도 됩니다!
=> N번째큰수/실버3/10분/O

week02/BOJ_2800/괄호제거_연예림.java
- 알고리즘 종류: Stack, TreeSet
TreeSet : 요소의 중복을 허용하지 않고, 정렬을 보장하는 자료구조
1. 스택을 통해 괄호의 짝 위치 저장
2. 모든 괄호의 경우에 수에 따라 제거 <- 여기서 어떻게 구현해야할지 막혀서 찾아서 해결했습니다.
보통 이런 경우 재귀를 통해 해결한다고 합니다.
변경될 부분과 원상복귀할 부분을 나누어 재귀함수를 사용하며 모든 경우의 수를 가질 수 있습니다. 
```java
int[] index = loc.get(depth);
// 해당 괄호를 포함하지 않는 경우 (변경될 부분)
check[index[0]] = true;
check[index[1]] = true;
comb(depth+1, str);
// 해당 괄호를 포함하는 경우 (원상복귀)
check[index[0]] = false;
check[index[1]] = false;
comb(depth+1, str);
```
또한 결과값이 중복되는 경우 `(((a))b)` 가 있을 수 있어 TreeSet으로 중복을 제거하며 정렬합니다.
```java
result = new TreeSet<>(); // 정렬 저장, 중복제거
```
경우의 수를 어떻게 찾아낼지 많이 고민되었던 문제였습니다.
=> 괄호제거 / 골드4 / 60분 / X

baekjoon-algorithm-study.iml, week02/BOJ_21942/부품대여장_한성지.java, week02/BOJ_2800/괄호제거_한성지.java
- 알고리즘 종류: 재귀함수
- 알고리즘 개념 간단 설명: 함수에서 자기 자신을 다시 호출해 작업을 수행하는 방식
1. 스택을 이용해 괄호쌍 위치 저장
2. 재귀함수를 통해 괄호 삭제 및 표시를 반복하며 모든 경우의 수를 TreeSet에 저장 후 출력
=> 괄호제거 / 골드4 / 30분 / X

baekjoon-algorithm-study.iml, week01/BOJ_10866/덱_한성지.java, week01/BOJ_1158/요세푸스문제_한성지.java, week01/BOJ_18258/큐2_한성지.java, week01/BOJ_1874/스택수열_한성지.java, week01/BOJ_9012/괄호_한성지.java, week02/BOJ_11279/최대힙_한성지.java
- 알고리즘 종류: 우선순위 큐
- 알고리즘 개념 간단 설명: 데이터가 들어온 순서대로 나가는 것이 아닌, 우선순위가 높은 데이터가 먼저 나가는 자료구조
1. 우선순위 큐 생성
2. x가 자연수인 경우 힙에 add하고, 0인 경우 첫번째 요소(루트) 반환 및 제거 (heap이 비어있는 경우 0 반환)
=> 최대힙 / 실버2 / 20분 / O

baekjoon-algorithm-study.iml, week01/BOJ_10866/덱_한성지.java, week01/BOJ_1158/요세푸스문제_한성지.java, week01/BOJ_18258/큐2_한성지.java, week01/BOJ_1874/스택수열_한성지.java, week01/BOJ_9012/괄호_한성지.java, week02/BOJ_11279/최대힙_한성지.java, week02/BOJ_1620/나는야포켓몬마스터이다솜_한성지.java
- 알고리즘 종류: HashMap
- 알고리즘 개념 간단 설명: key와 value를 한 쌍으로 갖는 자료형
1. 포켓몬 번호를 key로 하는 hashMap과 포켓몬 이름을 key로 하는 hashMap 생성 (포켓몬 도감)
2. 반복문을 통해 포켓몬 도감 채움
3. 문제를 int로 변환 (try-catch문으로 감쌈)
3-1. (try) 문제가 도감 번호일 경우 포켓몬 번호를 key로 하는 도감에서 답 검색
3-2. (catch) 문제가 포켓몬 이름일 경우 NumberFormatException이 발생하여 catch문으로 이동, 포켓몬 이름을 key로 하는 도감에서 답 검색
=> 나는야포켓몬마스터이다솜 / 실버4 / 30분 / O

week02/BOJ_11279/최대힙_이유빈.java
- 알고리즘 종류: Heap
- 알고리즘 개념 간단 설명: 힙이란 완전이진트리의 형태로, 중복이 가능하고 정렬 순서에 따라 최대힙, 최소힙으로 구분할 수 있다. 최대힙의 경우 내림차순으로 정렬되고 최소힙의 경우 오름차순으로 정렬된다.
1. 최대힙 자료구조 생성
2. 입력받은 문자열이 0이고 힙이 비어있을 때 0 출력
3. 입력받은 문자열이 0이고 힙이 비어있지 않을 때 힙의 최대값 출력
4. 입력받은 문자열이 0이 아닐 때 힙에 추가
=> 최대힙 / 실버2 / 15분 / O

week02/BOJ_21942/부품대여장.java
- 알고리즘 종류: HashMap, TreeMap
키와 값으로 저장되는 자료구조로 순서 정렬이 필요없는 건 HashMap, 순서 정렬이 필요한 건 TreeMap을 사용한다.
1. 시간을 모두 받아 분 단위로 변환한다.
```java
long current = toMinutes(st.nextToken(), st.nextToken());
```
2. Map의 키값을 이름과 제품명을 통해 HashMap 저장한다.
- 조건만족
```
한 사람이 같은 시각에 서로 다른 종류의 부품들을 대여하는 것이 가능하다.
```
```java
String id = String.join("_", product, name);
```
3. 같은 키가 있다면 리스트에서 지움과 동시에 분 차이를 계산하여 TreeMap에 저장한다.
-> 데이터 크기에 따른 타입오류나 
` 한 사람이 같은 시각에 서로 다른 종류의 부품들을 대여하는 것이 가능하다.` 조건 때문에 여러모로 힘들었네요,,ㅎㅎ
=> 부품대여장 / 골드2 / 100분/ O

week01/BOJ_9012/괄호_이유빈.java
- 알고리즘 종류: Stack
1. 입력된 문자열을 char로 쪼갬
2. 열린 괄호가 들어오면 stack에 저장
3. 닫힌 괄호가 들어왔을 때 stack이 비어있으면 vps를 만족하지 않으므로 NO, 해당 루프 종료
4. 닫힌 괄호가 들어왔지만 stack이 비어있지 않으면 pop
5. 모든 char에 대해 확인했으면 stack이 비어있는지 확인
6. 비어있으면 vps 만족 -> YES
7. 비어있지 않으면 vps 불만족 -> NO
=> 괄호 / 실버4 / 47분 / X

week02/BOJ_1620/나는야포켓몬마스터이다솜_이유빈.java
- 알고리즘 종류: HashMap
- 알고리즘 개념 간단 설명: key-value로 짝지어진 자료구조
포켓몬 이름이 key이고 번호가 value인 map1과
번호가 key이고 이름이 value인 map2를 생성 후
입력된 문자열이 map1에서 key로 존재하면 map1.get() 사용하여 번호 출력, 
map1에서 key로 존재하지 않으면 map2.get() 사용하여 이름 출력
HashMap을 하나만 사용하고 keySet()을 이용해 value에서 key를 찾아내려고 하니 시간초과가 발생하여 결국 HashMap을 두 개 사용했습니다. 
이 경우 추후에는 메모리 초과 문제가 발생할 위험도 있는데 어떻게 해결하면 좋을까요?
=> 나는야포켓몬마스터이다솜 / 실버4 / 21분 / O

week02/BOJ_11279/최대힙_민기.java
- **알고리즘 종류**: 최대 힙 (Max Heap) 활용
우선순위 큐를 내림차순 정렬(최대 힙)로 사용하여, 입력된 자연수들을 관리합니다.  
0이 입력될 때마다 힙에서 최대값을 꺼내 출력하고, 해당 값은 힙에서 제거됩니다.  
힙 삽입과 삭제 연산은 O(log N) 시간 복잡도를 가지므로 전체 연산은 O(N log N)입니다.
---
1. **입력 처리 및 초기화**:  
- `BufferedReader`로 연산의 개수 N을 입력받습니다.
- `PriorityQueue<Integer>`를 `Collections.reverseOrder()`로 초기화해 최대 힙을 구성합니다.
- 출력 결과를 모으기 위해 `StringBuilder`를 생성합니다.
2. **연산 처리**:  
- N개의 줄에 대해 정수 입력을 받고,  
- 만약 입력 값이 0이면, 힙이 비어있는지 확인 후 비어 있으면 "0", 아니라면 `poll()`을 호출해 최대값을 출력 결과에 추가합니다.  
- 입력 값이 양수이면, 힙에 추가합니다.
3. **최종 출력**:  
- `StringBuilder`에 누적된 결과를 한 번에 출력합니다.
---
- n번째 문제가 더 어려웠던것 같습니다
=> 최대힙 / 실버 2/ 15분 / O

week02/BOJ_11279/최대힙_민기.java, week02/BOJ_2075/N번째큰수_민기.java
- **알고리즘 종류**: 우선순위 큐(최대 힙)
주어진 N×N 행렬에서 “모든 수는 자신의 바로 위의 수보다 작다”는 성질을 활용해 각 열의 가장 큰 값을 마지막 행에서부터 우선순위 큐에 삽입합니다.  
우선순위 큐에서 최대값을 꺼내고, 같은 열의 바로 위의 값을 추가하는 방식으로 N번째 큰 수를 효율적으로 추출합니다.
---
1. **Cell 클래스**:  
- 행렬의 특정 위치와 그 값을 저장하는 간단한 데이터 구조입니다.
2. **findNthLargest 함수**:  
- **최대 힙 초기화**: 각 열의 마지막 행에 있는 값을 Cell 객체로 최대 힙에 삽입합니다.
- **N번째 큰 수 추출**: 우선순위 큐에서 최대값(Cell)을 반복적으로 poll한 후, 해당 셀의 바로 위 셀(같은 열에서)을 힙에 추가합니다.  
N번째 poll한 Cell의 값이 N번째 큰 수가 됩니다.
3. **main 함수**:  
- BufferedReader와 StringTokenizer를 활용하여 N×N 행렬의 데이터를 입력받아 배열에 저장합니다.
- findNthLargest 함수를 호출해 결과를 얻고 출력합니다.
---
- 코드 피드백해주시면 감사하겠습니다~
---
=> N번째큰수/실버3/40분/O

baekjoon-algorithm-study.iml, week01/BOJ_18258/큐2_연예림.java
- 알고리즘 종류: 큐
Queue는 FIFO 구조로 선입선출의 특징을 가지는 자료구조입니다.
이 문제가 처음으로 풀었던 문제입니다.
처음에 Scanner를 사용해서 시간 초과가 났었습니다. 
```
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
StringBuilder sb = new StringBuilder();
```
버퍼를 통해 읽어오는 방식이나 StringBuilder로 결과를 만들어내는 방식을 찾아보았습니다.
중간 중간에 sout 하는 방식은 역시 시간을 많이 잡아먹더라구요.
큐를 생성할 때, 가장 최근에 넣었던 값을 가져오기위해 Deque 을 사용하였습니다. 
피드백은 감사히 받겠습니다!
=> 큐2 / 실버4 / 40분 / X

week02/BOJ_11279/최대힙_민기.java, week03/BOJ_11725/트리의부모찾기_김준우.java
- 알고리즘 종류: DFS
- 알고리즘 개념 간단 설명: DFS는 트리에서 모든 정점을 탐색하는 알고리즘 중 하나로 한 방향으로 탐색을 계속해서 진행하며, 더 이상 탐색할 수 없으면 다시 되돌아와서 다른 경로를 탐색합니다.
- 먼저 트리는 이차원 배열로 구현하였습니다. 그리고 DFS는 재귀를 사용해서 구현을 했습니다.
- DFS를 하면서 해당 노드의 부모 노드를 결과로 출력할 배열에 담는 방식으로 진행하였습니다.
- 궁금하신 점 있으면 언제든 물어봐주세요!
=> 트리부모찾기/실버2/30분/X

week03/BOJ_2960/에라토스테네스의체_한성지.java
- 알고리즘 종류: 구현
1. 값을 받아 arrayList에 채움
2. list를 순회하며 현재 수가 소수인지 검사
```java
public static boolean isPrime(int num) {
for (int i = 2; i < num / 2; i++) {
if (num % i == 0) {
return false;
}
}
return true;
}
```
3. 소수인 경우 카운트를 올리고 해당수를 삭제, 그 배수도 삭제, 이 과정에서 카운트가 k와 동일해지면 반복문 탈출 후 정답 출력
=> 에라토스테네스의체 / 실버4 / 30분 / O

week03/BOJ_20364/부동산다툼_민기.java
- **알고리즘 종류**: 이진 트리 순회 (Binary Tree Traversal)
- **알고리즘 개념 간단 설명**  
- 이진 트리에서 특정 노드의 부모는 현재 노드 번호를 2로 나눈 값 (cur/2)
- 루트에서 특정 노드까지의 경로를 찾기 위해 역순으로 부모를 찾아가는 방식 사용
- ArrayList와 Collections.reverse()를 활용하여 실제 이동 경로 구성
- `boolean[] isChecked` 배열로 각 땅의 점유 여부를 관리
- ArrayList를 사용해 현재 위치(x)에서 루트(1)까지의 경로를 저장하고 reverse
- 경로상에서 처음 만나는 점유된 땅을 찾아 출력
- 점유된 땅이 없으면 원하는 땅(x)을 점유하고 0 출력
- 각 쿼리당 경로 탐색: O(log N) (이진 트리의 높이)
- 전체 시간복잡도: O(Q * log N)
- 코드 피드백해주시면 감사드리겠습니다~
=> 부동산다툼 / 실버 1 / 30분 / X

week03/BOJ_11725/트리의부모찾기_민기.java
- **알고리즘 종류**: DFS (Depth First Search)
- **알고리즘 개념 간단 설명**  
- 무방향 트리에서 루트(1번)를 기준으로 각 노드의 부모를 찾는 문제
- DFS를 통해 현재 노드에서 인접한 노드들을 방문하며 부모-자식 관계를 결정
- 인접 리스트를 활용하여 각 노드의 연결 정보를 저장하고 탐색
- `List<Integer>[] tree`: 각 노드의 인접 노드들을 저장하는 인접 리스트 배열
- `int[] parent`: 각 노드의 부모 노드 번호를 저장하는 배열
- DFS를 통해 루트(1번)부터 시작하여 연결된 모든 노드를 방문하며 부모 정보를 기록
- 무방향 트리이므로 이미 방문한 부모 노드로의 재방문을 방지하는 로직 포함
- 트리 구성: O(N) (N-1개의 간선 정보 입력)
- DFS 탐색: O(N) (각 노드를 한 번씩 방문)
- 전체 시간복잡도: O(N)
- 인접 리스트: O(N) (각 노드마다 연결 정보 저장)
- 부모 배열: O(N)
- 전체 공간복잡도: O(N)
-
=> 트리의부모찾기/실버2/30분/X

week03/BOJ_21275/폰호석만_김준우.java
- 알고리즘 종류: 진법 변환
- 알고리즘 개념 간단 설명: 문제에서는 2진법부터 36진법까지 각각의 진법을 십진법으로 변환할 수 있는지가 중요한 포인트였습니다.
각 진법에서 사용 가능한 숫자와 문자를 이해하는 것이 중요합니다.
- 2진수: 0, 1
- 10진수: 0 ~ 9
- 16진수: 0 ~ 9 , a ~ f 
- 36진수: 0 ~ 9 , a ~ z
문제에서는 주어진 두 개의 문자열이 같은 10진수 값을 가질 수 있는 (X, A, B) 조합을 찾아야 합니다. 여러 개의 가능한 (X, A, B) 조합이 존재하면 "Multiple", 가능하지 않으면 "Impossible", 단 하나만 존재하면 X A B를 출력합니다.
특정 진법의 문자열을 10진수로 변환하는 함수를 구현했습니다.
(변환 과정에서 result = result * base + digit 방식을 사용해 자릿수를 계산하였습니다)
2 ≤ A, B ≤ 36 범위에서 입력된 두 개의 값이 어떤 진법에서 동일한 10진수를 가질 수 있는지 확인했습니다.
이해가 어려운 부분이 있다면 언제든 질문해주세요! 😊
=> 폰호석만/실버2/50분/X

week03/BOJ_1991/트리순회_김준우.java
- 알고리즘 종류: 트리 순회
- 알고리즘 개념 간단 설명: 트리를 순회하는 방법은 총 3가지가 있습니다. 
- 전위 순회 : 루트 -> 왼쪽 자식 -> 오른쪽 자식 순서로 노드를 방문하는 방법
- 중위 순회 : 왼쪽 자식 -> 루트 -> 오른쪽 자식 순서로 노드를 방문하는 방법
- 후위 순회 : 왼쪽 자식 -> 오른쪽 자식 -> 루트 순서로 노드를 방문하는 방법
- 패턴을 살펴보면 루트 노드를 방문하는 시점에 따라 나뉘는 것을 알 수 있습니다.
- 노드 클래스를 생성해서 트리를 구성하도록 하였습니다.
- 노드에 들어갈 데이터를 입력으로 받을 때 해당 노드들을 연결할 부모 노드에 대한 탐색이 필요했습니다. 왼쪽 서브트리 탐색 후 오른쪽 서브트리를 탐색하는 순서로 트리를 탐색하는 코드를 작성했습니다.
- 궁금하신 점 있으시면 언제든 물어봐주세요!
=> 트리순회/실버1/30분/O

week03/BOJ_11725/트리의부모찾기_연예림.java
- 알고리즘 종류: DFS
깊이 우선 탐색으로 트리구조를 통해 구현됩니다.
방문한 노드에서 연결된 마지막 노드까지 탐색하고 다음 노드를 탐색합니다.
1. 각 노드의 연결된 노드 리스트를 바로 가져올 수 있도록  ArrayList를 사용했습니다.
2. 각 노드 리스트는 삽입/삭제가 빠르도록 LinkedList를 사용했습니다.
3. 방문한 노드의 부모 노드를 기록하기 위해 DFS를 사용하여 방문 기록 시 부모노드를 기록했습니다.
```java
static void dfs(int start) {
Deque<Integer> dq = new LinkedList<>();
dq.offer(start);
parents[start] = start;
while (!dq.isEmpty()) {
int parent = dq.pollLast();
// 넣을 때 기록하기
List<Integer> pollList = graph.get(parent);
for (int i = 0; i < pollList.size(); i++){
int addNode = pollList.get(i);
if (parents[addNode] == 0) {
dq.offer(addNode);
parents[addNode] = parent;
}
}
}
}
```
처음엔 bfs로 풀까 했는데, 부모 노드를 넣을때 갱신하는 느낌으로 해야할 것 같더라구요. 다른 분들은 어떻게 풀으셨나요
=> 트리의 부모 찾기 / 실버2 / 40분 / O

week03/BOJ_2960/에라토스테네스의체_연예림.java
- 알고리즘 종류: 에라토스테네스의 체
N보다 작서나 같은 모든 소수를 찾는 알고리즘
2부터 시작해서 배수가 되는 값들을 지워나가는 방식이다.
1. N+1개의 boolean 배열을 생성하여 지워졌는지 확인한다.
2. 2부터 시작해서 모든 값들의 배수를 지우는 것을 반복한다.
```java
static int getK() {
int cnt = 0;
for (int i = 2; i < arr.length; i++) {
for (int j = i; j < arr.length; j+=i) {
if (!arr[j]) {
arr[j] = true;
cnt++;
}
if (cnt == K) {
return j;
}
}
}
return 0;
}
```
=> 에라토스테네스의채 / 실버3 / 15분 / O

week02/BOJ_11279/최대힙_민기.java, week03/BOJ_2960/에라토스테네스의체_김준우.java
- 알고리즘 종류: List 자료구조
- 처음에는 리스트를 정렬한 후, 가장 작은 소수를 찾는 추가 코드가 필요할 것이라고 생각했습니다. 하지만 리스트가 2부터 N까지 순차적으로 저장된다는 점과, 가장 작은 수의 배수를 모두 지운다는 점을 고려하면, 별도의 정렬 과정이 필요하지 않다는 결론을 내렸습니다. 따라서, 가장 작은 수는 항상 배열의 맨 앞에 위치하므로, 이를 선택한 후 해당 수의 배수를 제거하는 방식으로 코드를 구현했습니다.
- 제가 작성한 코드에 궁금하신 점이 있다면 언제든 물어보세요!
=> 에라토스테네스의체/실버4/25분/O

week03/BOJ_1991/트리순회_연예림.java
- 알고리즘 종류: 트리순회
출력만 하는 문제이기 때문에 StringBuilder에 입력하고 한번에 출력하는 식으로 했습니다. 
여기서는 알파벳이 key로 사용되어 HashMap을 사용했는데, 최대 개수가 정해져 있기 때문에 알파벳을 숫자로 변환해서 배열로 했어도 괜찮을 것 같습니다.
ex) `grahp[26][2]`
저는 `HashMap (key, [left, right])` 이런 식으로 했었습니다.
=> 트리순회 / 실버1 / 20분 / O

week03/BOJ_20364/부동산다툼_연예림.java
- 알고리즘 종류: 단순 반복문
- dfs로 풀 수도 있지만, 연산을 통해 계산하면 빠르게 구할 수 있을 것 같아 다른 방법을 사용했습니다.
1. 처음 풀이한 방법
// 땅 수만큼 area 배열 생성
// 도달하려는 땅에서 시작 -> 1까지 /2 연산
// 1에 도달하기 전에 점유된 땅을 만나면 noArea(deque) 추가
// noArea(deque) 가 null이 아니면 가장 첫번째(가장 먼저 만나는 땅)를 출력
// noArea가 null이면 0 출력하고 점유된 땅으로 체크
2. 변경한 부분
// 처음 만난 점유된 땅만 확인하면 되므로 마지막에 저장된 변수로 확인 (필요한 값만 저장)
=> 이 부분을 바꾸고 나니 메모리 사용과 시간이 1/3 이나 줄었습니다:)
```java
for (int i = 0; i < ducks.length; i++) {
int last = -1;
int to = ducks[i];
while (to > 0) {
if (area[to]) {
last = to;
}
to /= 2;
}
if (last == -1) {
area[ducks[i]] = true;
sb.append(0).append("\n");
} else {
sb.append(last).append("\n");
}
}
```
저는 트리보다는 단순 연산으로 푼 것 같네요. 다들 트리고 푸셨나요?
=> 부동산 다툼 / 실버1 / 30분 / O

week03/BOJ_2960/에라토스테네스의체_박유진.java
- 알고리즘 종류: 수학-소수판별, 구현
```java
List<Integer> primes = new ArrayList<>();
```
```java
// 각각의 수를 돌면서 소수인지 검사
for (int i = 2; i <= n; i++) {
map.put(i, true);
boolean isPrime = true;
for (int j = 0; j < primes.size(); j++) {
// 앞에서 배열에 저장했던 소수들을 가지고 나눠보고 나누어진다면 소수가 아니므로 fasle
if (i % primes.get(j) == 0){
isPrime = false;
break;
}
}
if (isPrime) { // 소수라면, 이미 저장했던 소수로는 나누어지지 않았으므로 true 그대로
primes.add(i);
}
}
```
```java
int primeIdx = 0; // primes[0]에는 2가 들어있음
while (k > 0) { // k번 반복
int i = 1; // 배수를 구하기 위한 변수 
while (primes.get(primeIdx) * i <= n) { //  소수의 배수들 모두 찾기 위해 반복 
if (map.get(primes.get(primeIdx) * i)) { // 만약 아직 제거되지 않은 수라면
map.put(primes.get(primeIdx)*i, false);  // 제거 처리
k—; // 제거했으므로 k-1 
if (k == 0) { // 마지막으로 제거된 수
System.out.println(primes.get(primeIdx)*i);
break;
}
}
i++; …
```
=> 에라토스테네스의체 / 실버4 / 44분 / O

week03/BOJ_1991/트리순회_박유진.java
알고리즘 종류: 트리, 재귀, 트리 순회
```java
static class Node{
String ch;
Node leftChild;
Node rightChild;
Node(String ch){
this.ch = ch;
this.leftChild = null;
this.rightChild = null;
}
}
```
```java
// 각 알파벳은 중복 X 이므로, map을 통해서 노드 정보를 저장
Map<String, Node> tree = new HashMap<>();
int n = Integer.parseInt(br.readLine());
for (int i = 0; i < n; i++) {
String c = st.nextToken(); // 부모
String lc = st.nextToken();// 왼쪽 자식
String rc = st.nextToken(); // 오른쪽 자식
tree.putIfAbsent(c, new Node(c)); // 각 입력에서 부모 알파벳 노드 생성
if(!lc.equals(".”)){ // 왼쪽 자식으로 입력 받은 것이 .이 아니라면 자식 알파벳 노드 추가
tree.put(lc, new Node(lc));
tree.get(c).leftChild = tree.get(lc); // 부모 노드에 왼쪽 자식 노드 저장
}
if(!rc.equals(".”)){ 
tree.putIfAbsent(rc, new Node(rc)); 
tree.get(c).rightChild = tree.get(rc);
}
} …
```
=> 트리순회 / 실버2 / 85분 / O

week03/BOJ_2960/에라토스테네스의체_이유빈.java
- 알고리즘 종류: 에라토스테네스의 체
- 알고리즘 개념 간단 설명: 특정 정수(n) 이하의 모든 소수를 빠르게 구하는 알고리즘
n의 제곱근 이하인 정수까지만 확인하면 소수만 남음
ex) n=24면 24의 제곱근은 4.9이므로 4의 배수까지만 확인하면 모두 소수만 남음
1. 2부터 n까지 정수가 담긴 arr 생성
2. arr를 순회하며 해당 수가 소수인지 확인
3. 소수라면 해당 숫자와 그 수의 배수들 제거
4. 제거할 때마다 cnt + 1
5. cnt가 k와 동일해졌을 때의 수 확인
배수들 지우는 로직에서 애먹었다.
테스트케이스는 통과되는데 백준에서 자꾸 틀려서 오래걸림...
=> 에라토스테네스의체 / 실버4 / 66분 / O

week02/BOJ_11279/최대힙_민기.java, week03/BOJ_20364/부동산다툼_김준우.java
- 알고리즘 종류: 트리
- 문제에서 오리들이 1번 땅에서 시작한다고 하지만, 저는 오리들이 원하는 땅부터 시작해서 부모 땅으로 가는 방식으로 코드를 작성했습니다.
- 각 오리가 원하는 땅에 도달할 수 있는지 확인하기 위해, 부모 땅이 이미 점유되어 있으면 해당 오리는 더 이상 갈 수 없다는 특성을 활용했습니다.
- 예를 들어, 5번 땅에 가려면 5번 땅에서 시작해 부모인 2번 땅, 그 부모인 1번 땅을 차례대로 확인하면 됩니다. 이 방법이 효율적이라고 생각했습니다.
=> 부동산다툼/실버1/45분/O

week03/BOJ_21275/폰호석만_연예림.java
- 알고리즘 종류: 완전탐색 (브루트포스)
- 알고리즘 개념 간단 설명:  모든 경우의 수를 다 확인해서 정답을 찾는 방법
아스키코드를 생각하지 못하고 자꾸 char 에서 숫자를 변환하다보니 복잡하게 생각했던 것 같습니다. 결국 풀지 못하고 아래 글을 참고했습니다.
여러 글을 봤는데 아래 포스트가 잘 설명된 것 같습니다.
<a href="https://seung-yo.tistory.com/entry/%EC%88%98%ED%95%99-%EB%B0%B1%EC%A4%80-21275-%ED%8F%B0-%ED%98%B8%EC%84%9D%EB%A7%8C">[수학] 백준 21275 폰 호석만</a>
1. 값 확인이 쉽도록 1~9, a~z 를 아스키코드 값으로 배열에 저장
2. 해당 진법으로 변환 가능한지 확인
3. 가능하면 십진수로 변환
4. 같은 십진수가 있다면 count 증가
그래도 조금 이해가 안되는 부분이 있었는데요.
```java
static boolean check(int a, String s) {
for (int i = 0; i < s.length(); i++) {
// 최대 진법이 a 보다 큰 경우 (답 보면 크거나 같은 경우기는 함.)
if (arr[s.charAt(i)] >= a){
return false;
}
}
return true;
}
```
check 부분에서 ` arr[s.charAt(i)] >= a` 를 보면 진법이 같은 경우도 제외하고 있는데 왜 그런지 모르겠습니다:)
=> 폰호석만 / 실버2 / 60분 / X

week03/BOJ_21275/폰호석만_이유빈.java
- 알고리즘 종류: 진법 변환, 완전탐색
- 알고리즘 개념 간단 설명: 모든 진법 변환 결과값을 완전탐색하여 결과 도출
X가 어떤 진법으로 변환되었는지 확인하기 위해 2진법부터 36진법까지 완전탐색 진행
입력된 String을 char로 변환하여 10진법으로 바꿈
서로 다른 진법으로 동일한 10진법 수가 생성되는지 확인
=> 폰호석만 / 실버2 / 30분 / X

week03/BOJ_1991/트리순회_이유빈.java
- 알고리즘 종류: 트리, 재귀
1. key는 부모 노드 값을 담는 String이고 value는 left node, right node를 담는 String 기반 ArrayList인 Map 생성
2. preOrder, inOrder, postOrder 각각 구현
=> 트리순회 / 실버1 / 76분 / X

week03/BOJ_11725/트리의부모찾기_이유빈.java
- 알고리즘 종류: BFS(넓이 우선 검색)
- 알고리즘 개념 간단 설명: 루트 노드에서 시작해서 인접한 노드를 먼저 탐색하는 방법
1. 부모 노드를 저장할 배열 생성
2. 방문했는지 체크하는 배열 생성
3. 트리의 구조를 저장하는 연결 리스트 생성
4. 연결 리스트에 트리 구조 저장
5. BFS를 위한 큐 생성
6. 현재 노드의 자식 노드들 탐색
7. 다음 노드의 부모가 현재 노드임을 parent 배열에 저장
=> 트리의부모찾기 / 실버2 / 30분 / X

week03/BOJ_20364/부동산다툼_이유빈.java
- 알고리즘 종류: 트리
- 알고리즘 개념 간단 설명: 트리의 루트에서부터 검색하는 것이 아니라 아래에서부터 검색하는 것이 더 편함
1. 다른 오리가 땅을 점유했는지 파악하기 위한 visited boolean 배열 생성
2. 각 오리가 어떤 땅을 원하는지를 담은 배열 생성
3. 원하는 땅에서부터 거꾸로 올라오며 땅을 가질 수 있는지 없는지 검사
=> 부동산다툼 / 실버1 / 47분 / X

week03/BOJ_20364/부동산다툼_한성지.java
- 알고리즘 종류: 트리
1. root에서부터 원하는 땅까지 찾아가는 방식이 아닌 원하는 땅에서 root를 가는 방식으로 작성
2. root 가는 도중에 점유된 땅 발견 시 해당 땅 번호를 출력
3. 원하는 땅 점유 성공 시 0 출력
=> 부동산다툼 / 실버1 / 30분 / X

week04/BOJ_14916/거스름돈_김준우.java
- 알고리즘 종류: 그리디
- 알고리즘 개념 간단 설명: 그리디 알고리즘은 가장 최선의 선택을 함으로써 최적의 해를 구하는 알고리즘
하지만 그리디 알고리즘이 최적의 해를 보장해주지 않는다!
- 거스름돈을 줄 수 있는 동전이 2, 5원으로 제한되어 있었습니다. 1원 단위가 없으니까 거슬름돈을 거슬러 줄 수 없는 상황도 발생했습니다.
- 거스름돈을 줄 때 동전의 개수를 가장 적게 주는 방법은 가장 큰 단위를 최대한 많이 사용하면 됩니다. 
- 1원, 10원, 100원 과 같이 단위가 부분합 관계일 때는 최적의 해를 보장하지만 2원, 5원, 7원 단위 처럼 서로가 부분합 관계가 아닐 때는 최적의 해를 보장하지 못하므로 다른 방법을 고민
- 여기서는 단위가 2개뿐이므로 거스름돈이 입력으로 주어질 때 해당 값이 5로 나눠지는지 확인 후 2를 빼면서 해당 값이 5로 나누어지는지 계속 확인하는 방식으로 코드를 작성해보았습니다.
- 최악의 경우는 입력값이 한 번도 5로 나누어지지 않는 때로 시간복잡도는 O(N)으로 예상됩니다.
- 이해가 안되는 부분이 있다면 언제든지 물어봐주세요
=> 거스름돈/실버5/35분/X

week04/BOJ_21314/민겸수_연예림.java
1, 가장 큰 값인 경우 -> k를 기준으로 가장 크게 묶는 경우
- k가 나올 때 까지 m count 증가 -> k가 나오면 5를 넣고 m count 만큼 0 추가
- 단, 마지막 묶음이 k가 없는 경우 모두 m count 만큼 1로 처리한다.
2. 가장 작은 값인 경우
- M 과 K를 모두 분리하되 M은 붙어있을때 같은 묶음으로 처리한다.
- k가 나올 때까지 m count -> m count -1 만큼 0 추가, k는 5 추가
- 모든 반복을 마친 후에 남은 m 도 위와 같이 처리한다.
```java
public static String getMax(String str) {
// k를 기준으로 가장 크게 묶는 경우
// k가 나올때까지 m count -> k가 나오면 5를 넣고 m count 만큼 0추가
StringBuffer sb = new StringBuffer();
int mCnt = 0;
for (int i = 0; i < str.length(); i++) {
if (str.charAt(i) == 'M') {
mCnt++;
} else if (str.charAt(i) == 'K'){
sb.append("5").append("0".repeat(mCnt));
mCnt = 0;
}
}
// 단, 마지막 묶음이 k가 없는 경우 모두 m(1) 으로 처리한다.
if (mCnt != 0) {
sb.append("1".repeat(mCnt));
}
return sb.toString();
}
```
O(n)
=> 민겸수 / 실버1 / 50분 / O

week04/BOJ_20115/에너지드링크_연예림.java
규칙을 찾아서 단순 연산하는 방식을 사용했습니다.
max 값을 제외한 모든 값을 2로 나누고 더하면 최대 양을 구할 수 있습니다.
```java
// max 값 찾기, max가 아닌 값 들은 모두 2로 나누고 합치기
double total = 0;
int max = Integer.parseInt(input[0]);
for (int i = 1; i < input.length; i++) {
int next = Integer.parseInt(input[i]);
if (next > max) {
// next를 max에 넣고
int temp = max;
max = next;
// max 값을 /2 하고 sum에 넣기
total += temp / 2.0;
} else {
total += next / 2.0;
}
}
total += max;
System.out.println(total);
```
- O(n)
=> 에너지드링크 /  실버3 / 30분 / O

week04/BOJ_14916/거스름돈_연예림.java
* 참고: 그리디 알고리즘에 대해 알아보기는 했지만 아래 문제에서 사용하지는 않았습니다.
현재 상황에서 최선의 선택만을 하는 알고리즘으로 매 순간 최선의 선택만을 하므로, 이후의 상황에 대해서는 전혀 고려하지 않는다.
- 그리디 알고리즘의 조건
1. 현재의 선택이 이후의 선택에 영향을 주지 않아야 한다.
2. 전체 문제의 최적 해결 방안이 부분 문제의 최적 해결 방안이어야 한다.
=> 이번 문제는 5원이 2원의 배수가 될 수 없어 2번의 조건을 만족하지 못해서 그리디로 풀 수 없는 문제입니다.
```java
public static int calcMoney(int num) {
// 만약 n 이 5 이하고 2, 4 가 아니라면
if (num < 5 && num % 2 != 0) {
return -1;
}
int m = num / 5;
int n = num % 5;
if (n == 0) {
return m;
} else if (n % 2 == 0) { // 나머지가 짝수인 경우
return m + (n / 2);
} else { // 홀수인 경우
return (m - 1) + ((n + 5) / 2);
}
}
```
O(1)
=> 거스름돈 / 실버5 / 20분 / O

week04/BOJ_20115/에너지드링크_김준우.java
- 알고리즘 개념 간단 설명: 그리디 알고리즘은 가장 최선의 선택을 반복적으로 수행하여 최적해를 구하는 알고리즘입니다. 하지만 최적해를 보장해주지는 못합니다.
- 음료를 따를 때 절반이 버려진다는 점에 착안하여, 최대로 만들 수 있는 음료의 양을 고민해 보았습니다. 음료를 절반씩 버리면서 합칠 때, 가장 적은 양의 음료부터 순차적으로 가장 많은 음료에 붓는 것이 최적의 방법이라는 것을 알게 되었습니다. 따라서, 배열을 정렬한 후, 가장 큰 용량의 음료에 나머지 음료의 절반씩을 더하는 방식으로 코드를 작성했습니다.
정렬 시에 최악의 경우 O(nlogn)의 시간복잡도
- 코드에 대해 궁금하신 점이 있다면 언제든 물어봐주세요
=> 에너지드링크/실버3/20분/O

week04/BOJ_21314/민겸수_김준우.java
- 알고리즘 종류: 그리디
- 민겸 수는 문자 1개를 숫자로 변환할 수 있고 여러 개의 문자를 숫자로 변환할 수 있다. 여기서 최대, 최소를 구하기 위해서는 앞자리가 중요한데, 최대값인 경우에는 K가 나오면 먼저 5를 변환하고 K가 나오기 이전에 나온 M의 개수만큼 5 뒤에 0을 붙인다. 그리고 만약 K가 나오지 않는다면 M은 1로 변환한다.
- 최소값인 경우에는 K가 나온다면 만약 그전에 M이 나온적이 있다면 먼저 1을 변환하고 K 이전의 나온 M의 개수 - 1만큼 1 뒤에 0으로 붙인다. 만약 M이 나온적이 없다면 K는 그냥 5로 변환한다. 만약 K가 나온적이 없다면 1을 변환하고 그 뒤에 M의 개수 - 1 만큼 0으로 붙인다.
- 이 코드는 문자열 길이에 선형적으로 비레함으로 O(N)
- 코드에 대해 궁금하신 점이 있다면 언제든 물어봐주세요
=> 민겸수/실버1/25분/O

week04/BOJ_11000/강의실배정_김준우.java
- 알고리즘 종류: 그리디
- 처음에는 시작 시간과 끝나는 시간을 필드로 갖는 수업 객체를 만든 후 정렬해서 사용할 생각이었습니다. 
- 이번 문제는 최소한의 강의실 개수를 출력하는 것이기 때문에 굳이 수업 객체를 만들 필요가 있을까라는 생각이 들어 이와 같은 코드를 작성해보았습니다.
- 시작 시간과 끝나는 시간을 배열에 각각 담고 정렬 후, 시작 시간을 끝나는 시간과 비교하여 만약 끝나는 시간보다 크거나 같다면 끝나는 시간 배열을 한 칸 이동시키고 아니라면 roomCount를 1 증가시키는 방법으로 코드를 작성해보았습니다.
- 이 문제는 실제로 어떤 강의가 어떤 강의실에서 진행되는지는 따로 추적을 할 필요가 없기 때문에 강의들이 겹치는 여부만 판단해서 코드를 작성했습니다.
정렬로 인한 O(nlogn) 시간 복잡도를 보입니다.
- 궁금하신 점이 있다면 언제든 물어봐주세요!
=> 강의실배정/골드5/40분/X

week04/BOJ_21314/민겸수_한성지.java
- 알고리즘 종류: 탐욕법
1. 최대값의 경우 입력된 문자열을 K의 뒤를 기준으로 자른 뒤 숫자로 변환
2. 최소값의 경우 K의 앞뒤를 기준으로 자른 뒤 숫자로 변환
반복문으로 인해 O(N)
=> 민겸수 / 실버1 / 60분 / O

week04/BOJ_20115/에너지드링크_박유진.java
- 알고리즘 종류: 그리디 (탐욕)
- 알고리즘 개념 간단 설명: 최적의 해를 구하는 데에 사용되는 근사적인 방법이다. 여러 경우 중 하나를 결정해야 할 때마다 그 순간에 최적이라고 생각되는 것을 선택해 나가는 방식으로 진행하여 최종적인 해답에 도달하는 알고리즘이다. 
> 접근
많은 양의 에너지 드링크는 원래대로 놓고, 그보다 적은 에너지 드링크를 반만 붓게 되면 더 많은 양의 에너지 드링크(최적의 해)를 만들 수 있었습니다.
그래서 에너지 드링크 용량을 배열로 입력 받은 후, Array.sort(arr)을 이용하여 정렬하였습니다. 그 후 가장 용량이 많은 에너지 드링크는 그대로 담아놓은 채로 그보다 적은 에너지 드링크들을 반씩 줄여 누적합 하는 방식으로 최적해를 구하였습니다.
- 직접 구현한 부분: O(n)
- Array.sort() : 평균 : O(nlog(n)) / 최악 : O(n^2)
- 출처: https://yuja-kong.tistory.com/183
=> 에너지드링크 / 실버3 / 12분 / O

week04/BOJ_11399/ATM_박유진.java
- 알고리즘 종류: 그리디
- 알고리즘 개념 간단 설명:  ‘각 단계에서 최적이라고 생각되는 것을 선택’ 해 나가는 방식으로 진행하여 최종적인 해답에 도달하는 알고리즘입니다. 항상 최적의 값을 보장하는것이 아니라 최적의 값의 ‘근사한 값’을 목표로 한다. 주로 문제를 분할 가능한 문제들로 분할한 뒤, 각 문제들에 대한 최적해를 구한 뒤 이를 결합하여 전체 문제의 최적해를 구하는 경우에 주로 사용됩니다.
- 인출하는데 걸리는 시간이 긴 사람이 먼저 인출을 하는 경우, 대기시간이 모두 길어진다는 점을 깨닫고 인출 시간이 짧은 사람부터 우선적으로 인출을 하여 대기시간을 줄이고자 하였습니다. 그래서 인출 시간 오름차순으로 정렬한 후, 각 사람별 인출 대기시간을 누적합으로 구하고, sum에 그 대기시간을 더하는 방식으로 구현하였습니다. 
- 직접 구현한 부분: O(n)
- Array.sort() : 최악 O(n^2)  / 평균 O(nlog(n)) 
에너지 드링크 문제와 ATM문제 모두 Arrays.sort()가 익숙하여 해당 메소드를 사용하였는데, 고레벨의 문제에서는 Arrays.sort()를 사용하는 경우 시간초과가 발생할 수 있다는 글을 보았습니다. Collections.sort()의 경우 평균과 최악 모두 O(nlog(n))이라 최악의 경우의 시간복잡도가 더 적기 때문에 앞으로는 Collections.sort()를 사용해야겠습니다... 
- _
=> ATM / 실버4 / 27분 / O

week04/BOJ_11000/강의실배정_한성지.java
- 알고리즘 종류: 우선순위 큐
- 알고리즘 개념 간단 설명: 우선순위가 높은 데이터가 먼저 나가는 구조의 큐
1. Lecture 클래스 정의 - 시작 시간과 종료 시간 저장
2. 배열에 Lecture를 저장한 뒤 시작 시간을 기준으로 오름차순 정렬(시작 시간이 같은 경우 종료시간 기준으로 정렬)
3. 우선순위 큐에 종료시간을 넣고, 가장 빨리 끝나는 강의의 종료 시간과 다음 강의의 시작 시간을 비교해 시작 시간이 같거나 느릴 경우 poll을 하고 아니면 바로 큐에 다음 강의의 종료 시간을 offer함
4. 큐의 최종 사이즈가 강의실 최소 개수
=> 강의실배정 / 골드5 / 30분 / X

week04/BOJ_21314/민겸수_민기.java
- 알고리즘 개념 간단 설명: (선택) : 
1. 최댓값 구하기:
- M이 연속으로 나올 때 K와 만나면 5xxx 형태로 처리
- 마지막에 남은 M은 모두 1로 처리
2. 최솟값 구하기:
- M이 연속으로 나올 때 가능한 빨리 처리 (1xxx 형태)
- K는 독립적으로 5로 처리
- O(N) : 각 문자를 한번씩 순회한다 생각하여 O(n)이라 생각하였다
- 최대값, 최소값 구하는 방법에 대해서 다른 방법도 있을것 같은데 풀이 방법에 대해 생각을 하지 못해서 다른 효율적인 방법이 있는지 궁금합니다.
=> 민겸수 / 실버1 / 40분 / X

week04/BOJ_20115/에너지드링크_민기.java
- 알고리즘 개념 간단 설명: 가장 큰 용량의 에너지 드링크를 기준으로 하고, 나머지 드링크들의 절반을 더해가는 방식으로 최적해를 구하는 알고리즘입니다.
1. PriorityQueue를 내림차순으로 구현하여 가장 큰 용량의 드링크부터 처리
2. 첫 번째로 가장 큰 용량의 드링크를 기준값으로 설정(이걸 잘못생각하여 서로 다른이라는 말을 보고 기준에 대해 생각을 못했다)
3. 남은 드링크들의 절반씩을 기준값에 더해가며 최대량 계산
4. 최종적으로 만들 수 있는 에너지 드링크의 최대량 출력
자료구조 | 삽입 | 삭제 | 검색
-- | -- | -- | --
PriorityQueue | O(log n) | O(n) | O(n)
TreeSet | O(log n) | O(log n) | O(log n)
SortedList | O(log n) | O(log n) | O(log n)
PriorityQueue보다 SortedList를 사용해볼까 했는데 SortedList는 삽입/삭제 할때 재정렬이 필요해서 priorityqueue가 가장 괜찮지 않나 생각을 하게 되었다.
PriorityQueue: 우선순위 기반 처리가 필요한 경우 (예: CPU 스케줄링))
TreeSet: 정렬된 고유 요소의 집합이 필요한 경우
SortedList: 키-값 쌍으로 정렬된 데이터가 필요하고 메모리가 제한적인 경우
- 우선 정렬을 해야겠다 생각했기에 priorityqueue 써봐서 그걸로 구현을 했는데 보니까 sortedlist나 treeset으로 하는게 시간복잡도 상으로 더 좋은것 같은데 다른 분들은 어떻게 …
=> 에너지드링크 / 실버4 / 30분 / X

week04/BOJ_11399/ATM_민기.java
인출 시간이 짧은 사람부터 우선적으로 처리해야겠다 싶어서 미리 넣은 후 자동 정렬을 할수 있는 자료구조를 정하면 좋을것 같았습니다.
따라서 PriorityQueue(최소 힙)을 사용하여 자동으로 오름차순 정렬 후, 누적합을 구하는 방식을 사용하였습니다.
- **우선순위 큐 삽입 및 삭제:** O(N log N)  
- **누적합 계산:** O(N²)  
누적합 계산을 할때 시간을 더 줄일 수 있을것 같은데 어떻게 줄여야 될지는 잘 모르겠습니다...
-
=> ATM / 실버4 / 28분 / O 

week04/BOJ_14916/거스름돈_박유진.java
- 알고리즘 종류: 그리디, 조합
- 각 동전별로 해당 동전만 사용해서 줄 수 있는 동전의 개수를 구한 후,
- 각 동전의 개수(경우의 수)를 조합하여 돌려주고자 하는 값 n 이 되었을때 해당 경우에서 동전의 수가 최소 개수 인지 계산
- 만약 2, 5의 동전으로 거슬러줄 수 없는 값이라면, flag 가 false이기 때문에 -1 출력
> 2, 5의 동전으로 거슬러 줄 수 없는 경우에 바로 -1을 출력하도록 할 수 있을 것 같은데, 좋은 방법이 떠오르지 않아서 그냥 flag를 사용했습니다.
- O(n^2)
=> 거스름돈 / 실버5 / 18분 / O

week04/BOJ_11399/ATM_연예림.java
처리시간이 적은 수부터 더해나가면 되는 문제였습니다.
정렬하기 위해 stream 이용 
-  Stream은 TimeSort 정렬을 사용
삽입 정렬과 합병정렬을 결합한 정렬
시간복잡도: `O(nlog(n)))`
```java
// 정렬하고 작은 수 부터 더하면 됨.
List<Integer> sortedList = Arrays.stream(strings)
.map(s -> Integer.parseInt(s))
.sorted()
.collect(Collectors.toList());
for (int n : sortedList) {
pre += n;
sum += pre;
}
```
O(n)
=> ATM / 실버4 / 20분 / O

week04/BOJ_11000/강의실배정_연예림.java
- 알고리즘 종류: 우선순위 큐
순서에 상관없이 우선순위가 높은 데이터가 먼저 나가는 구조
주로 힙을 통해 구현된다.
1. 입력 받을 강의 우선순위를 정하고 우선순위큐에 저장함
2. 강의실을 나타내고, 강의의 종료시간을 담운 우선순위 큐 room 생성
3. room에서 하나씩 값을 peek() 해서 비교하고 poll() 을 할지 결정한다.
=> 강의실배정 / 골드5 / 40분 / X

week04/BOJ_11000/강의실배정_민기.java
- 알고리즘 개념 간단 설명: 강의실 배정 시 시작 시간을 기준으로 정렬하고, 종료 시간을 우선순위 큐로 관리하여 최소 강의실 개수를 구하는 구조로 진행했습니다.
1. 강의 시작 시간을 기준으로 오름차순 정렬 (Hashmap을 이용해서 map<S,T>로 저장한 후 조회하려 했지만
지난번에도 똑같은 이슈가 있었던것 같은데 T의 값을 바로 찾을 수가없었기 때문에 이중배열로 저장하는 쪽으로 구현했습니다.)
2. 우선순위 큐를 사용하여 강의 종료 시간을 관리
3. 현재 강의 시작 시간이 가장 빨리 끝나는 강의실의 종료 시간보다 크거나 같으면 해당 강의실 재사용 만약 그렇제 않다면 새로운 강의실을 할당
4. 최종적으로 우선순위 큐의 크기가 필요한 최소 강의실 개수 출력으로 완료
강의 정렬: O(N log N)
우선순위 큐 연산: O(N log N)
-
=> 강의실배정 / 골드5 / 50분 / X

week01/BOJ_1874/스택수열_이유빈.java
=> 스택수열 / 실버2 / 30분 / X

week01/BOJ_10866/덱_이유빈.java
=> 덱 / 실버4 / 21분 / O

week01/BOJ_1158/요세푸스문제_이유빈.java
=> 요세푸스문제 / 실버4 / 27분 / O

week04/BOJ_11000/강의실배정_박유진.java
=> 강의실배정 / 골드5 / 59분 / X

week04/BOJ_20115/에너지드링크_한성지.java
- 알고리즘 종류: 탐욕법(그리디 알고리즘)
- 알고리즘 개념 간단 설명: 각 단계에서 최적이라고 생각되는 것을 선택해나가는 방식으로 진행하여 최종적인 해답에 도달하는 알고리
에너지 드링크 중 최대값을 먼저 answer에 더하고 내림차순으로 반씩 나누며 더하는 방식으로 답 구함
정렬 과정으로 인해 O(N log N)
=> 에너지드링크 / 실버3 / 50분 / O

week05/BOJ_5639/이진검색트리_연예림.java
- 알고리즘 종류: 이진 검색 트리
왼쪽 서브트리에는 해당 노드 보다 작은 값이, 오른쪽 서브트리에는 큰 값이 들어있고 중복된 노드가 없는 탐색트리입니다.
처음에 값을 바로 넣지 않고 부모 값과 비교하여 넣는 식으로 했었는데, 생각해보니 넣을 때 비교하면 되는 문제 였습니다 ^^;;
```java
public static Node createNode(Node node, int input) {
// 노드가 없으면 추가
if (node == null) {
return new Node(input, null, null);
}
// 현재 노드값보다 작으면 왼쪽 노드와 함께 넘김
if (node.value > input) {
node.left = createNode(node.left, input);
} else {
node.right = createNode(node.right, input);
}
return node;
}
```
=> 이진검색트리 / 골드4 / 40분 / O

week05/BOJ_9934/완전이진트리_연예림.java
- 알고리즘 종류: 완전이진트
마지막 노드를 제외하고 모든 레벨이 완전히 채워져 있는 트리, 마지막 레벨의 노드는  가장 왼쪽에 있다.
1. input 수 만큼의 노드를  가진 이진 트리 생성 (노드별 레벨 기록)
```java
// 필요한만큼만 노드 생성
maxCnt = input.length;
int level = 1; // 레벨 기록용
Node root = new Node(level++, returnNode(level, 2), returnNode(level, 3));
```
2. 레벨별 노드를 기록할 List 생성
3. 1에서 생성한 트리를 순회하며 각 노드의 레벨 기록
```java
// 탐색
static int i = 0;
public static void visit(Node node) {
if (node == null) {
return;
}
visit(node.left);
nodeLevel.get(node.level).add(input[i++]); // 레벨 기록
visit(node.right);
}
```
=> 완전이진트리 / 실버1 / 50분 / O

week05/BOJ_21919/소수최소공배수_한성지.java
- 알고리즘 종류: 수학
1. 소수 구하기
```java
static boolean isPrime(long num) {
if (num == 2) { // 2는 소수
return true;
}
if (num % 2 == 0) { // 짝수 걸러냄
return false;
}
// num이 소수가 아니면 반드시 그 수의 약수 중 하나는 num의 제곱근보다 작음
for (long i = 3; i * i <= num; i += 2) {  // 홀수만 검사
if (num % i == 0) {
return false;   // 소수가 아님
}
}
return true;    // 소수 맞음
}
```
2. 구한 소수를 Set에 담음
3. Set의 요소들을 곱해 최소공배수 출력
O(N)
=> 소수최소공배수 / 실버3 / 30분 / X

week05/BOJ_3584/가장가까운공통조상_한성지.java
- 알고리즘 종류: 트리
1. 주어진 노드의 부모자식 관계 저장
2. 타겟 노드 1을 루트까지 이동하며 true로 표시
3. 타켓 노드 2를 루트까지 이동하며, true로 표시된 곳을 만날 경우 그 곳이 가장 가까운 공통 조상 -> 출력
O(N)
=> 가장가까운공통조상 / 골드4 / 30분 / X

week05/BOJ_5639/이진검색트리_한성지.java
- 알고리즘 종류: 트리
전위순회한 결과를 트리로 바꾼 후 후위순회 결과물 출력
최악의 경우 O(N^2)
=> 이진검색트리 / 골드4 / 30분 / X

week05/BOJ_9934/완전이진트리_한성지.java
- 알고리즘 종류: 트리## ⭐️ 문제에서 주로 사용한 알고리즘
- 알고리즘 종류: 트리
중위순회 특성을 이용하여 레벨에 맞게 빌딩 값 저장
```java
static void search(int depth, int start, int end) {
int mid = (start + end) / 2;    // root 노드
tree.get(depth).add(num[mid]);  // 가장 첫 줄에 root 노드 저장
if (depth == K) {       // 단말 노드일 경우
return;
}
search(depth + 1, start, mid - 1);  // left
search(depth + 1, mid + 1, end);    // right
}
```
O(N)
=> 완전이진트리 / 실버1 / 30분 / X

week05/BOJ_21919/소수최소공배수_김준우.java
- 알고리즘 종류: 에라토스테네스의 체
- 알고리즘 개념 간단 설명:  에라토스테네스의 체는 소수 찾기를 위한 고전적인 알고리즘 기법으로 배열을 통해서 해당 값이 소수인지 아닌지를 기록하는 방법입니다.
- 어떤 숫자(n)가 소수인지 아닌지를 판별하기 위해서는 그 수가 1이 아닌 두 개의 수로 나눌 수 있는지를 판별해야 합니다. 이때 두개의 수 중 하나는 무조건 루트 n보다 작거나 같아야 한다는 특징이 있습니다.
- 예를 들어서 36은 2 * 18, 3 * 12, 4 * 9, 6 * 6 이처럼 2개의 수 중에 하나는 6보다 작거나 같습니다.
- 이러한 특징을 가지고 코드를 구현해보았습니다.
- O(nlogn)
- 코드에 대해서 궁금하신 점이 있다면 언제든 물어봐주세요
=> 소수최소공배수/실버3/45분/X

week05/BOJ_1669/멍멍이쓰다듬기_김준우.java
- 알고리즘 종류: 수학(완전 제곱 수)
- 먼저 원숭이와 멍멍이의 키의 차이를 구합니다.
- 키의 차이가 제곱수인지 제곱수가 아닌지를 판별해야 합니다.
- 키는 첫째날과 마지막 날에는 1cm만 키울 수 있고 키의 양은 1cm밖에 조절할 수 없기 때문에 키의 증가하는 모습을 숫자로 써보면 마치 산처럼 올라갔다가 내려오는 형태로 되어있음을 알 수 있습니다. 그렇다면 산 정상에 해당하는 가장 큰 수는 입력된 숫자의 제곱근과 같다는 것을 알 수 있습니다.
- 4 = 1 + 2 + 1 / 9 = 1 + 2 + 3 + 2 + 1
- 만약 키의 차이가 제곱수라면 키가 같아지는 최소의 일수는 2 * n - 1입니다. (이때 n은 키의 차이의 제곱근)
- 키의 차이가 제곱근이 아니라면 키가 같아지는 최소 일수는 2 * n - 1 + 1 or 2 * n - 1 + 2입니다.
- 만약 키의 차이 - n * n이 n보다 작거나 같다면 1만 더하면 되고, 키의 차이 - n * n이 n보다 크다면 2를 더하면 됩니다.
- O(1)
- 궁금하신 점이 있다면 언제든지 물어봐주세요!
=> 멍멍이쓰다듬기/골드5/40분/X

week05/BOJ_5639/이진검색트리_박유진.java
- 알고리즘 종류: 이진 검색 트리
- 알고리즘 개념 간단 설명:
이진 검색 트리(BST)는 효율적인 검색, 삽입, 삭제 연산을 지원하는 자료구조이다.
- 각 노드는 최대 두 개의 자식 노드를 가질 수 있다. (왼쪽 자식과 오른쪽 자식).
- 왼쪽 서브트리의 모든 노드는 부모 노드의 값보다 작다. ( 왼쪽 자식 모든 노드 < 부모 노드)
- 오른쪽 서브트리의 모든 노드는 부모 노드의 값보다 크다.( 부모 노드 < 오른쪽 모든 노드 )
- 중복된 값은 일반적으로 허용되지 않음 (구현에 따라 다를 수 있음)
이진 검색 트리에서 값을 찾는 과정:
1. 루트 노드부터 시작
2. 찾으려는 값이 현재 노드의 값과 같으면 검색 성공.
3. 찾으려는 값이 현재 노드보다 작으면 왼쪽 서브트리로 이동.
4. 찾으려는 값이 현재 노드보다 크면 오른쪽 서브트리로 이동.
5. 리프 노드까지 도달했는데 찾지 못했다면 해당 값은 트리에 없음.
새 값을 트리에 추가하는 과정:
1. 루트 노드부터 시작
2. 삽입할 값이 현재 노드보다 작으면 왼쪽으로 이동.
3. 삽입할 값이 현재 노드보다 크면 오른쪽으로 이동.
4. 적절한 위치(null 참조)에 도달하면 새 노드를 생성하여 삽입.
노드를 삭제하는 과정은 세 가지 경우로 나뉨:
1. 삭제할 노드가 리프 노드인 경우: 단순히 노드를 제거.
2. 삭제할 노드가 하나의 자식만 가진 경우: 자식을 부모에 직접 연결.
3. 삭제할 노드가 두 자식을 가진 경우: 중위 후속자(오른쪽 서브트리의 최소값)를 찾아 삭제할 노드와 교체하고, 중위 후속자를 삭제.
1. **중위 순회 (In-order)**: …
=> 이진검색트리 / 골드4 / 70분 / X

week05/BOJ_1669/멍멍이쓰다듬기_박유진.java
- 알고리즘 종류: 수학
- 참고: https://data-bank.tistory.com/40
```java
//키 차이를 구함
long sub = y-x;
if(sub == 0 ){ // 예외처리
System.out.println(0);
}
else{
// 멍멍이와 원숭이의 키차이보다 작은 수들 중 가장 큰 제곱수를 구하기 위해 루트 연산을 한 뒤, long으로 강제 형변환
long sqrt = (long) Math.sqrt(sub);
// 제곱수를 구함
long pow = sqrt * sqrt;
// 만약 키 차이와 제곱수가 같다면
if(sub == pow){ 
// 2 * n -1 일이 소요됨
//  n이 정수인 경우는 1, 2, 3, 2, 1 cm 와 같이 계단식이기 때문
System.out.println( 2* sqrt - 1);
}else{
// 루트(Y- X)가 정수가 아닌 경우, 
// 키차이에서 제곱수를 뺀 후 남은 값은, 계단식으로 증감을 하고 난 뒤의 Y와 X의 차이이다.
// 따라서 X와 Y가 같아져야 되는 최소의 일수를 구해야 한다. 즉, Z만큼 X의 크기를 증가시키면 된다.
sub = sub - pow;
// 나머지 키차이가 squrt 보다 작거나 같다면
if( sub <= sqrt ){
// 2 * n 일 소요
// 나머지 키가 N보다 작다면 하루만 더 사용하면 된다.
System.out.println(2*sqrt);
}else{
// 2*n +1 일 소요
// 나커지 키가 N보다 크면 1 ~ N까지의 수들 중 2개 합으로 나머지 키를 만들어야 하므로 이틀을 더 사용해야 한다 …
```
=> 멍멍이쓰다듬기 / 골드5 / 42분 / X

week05/BOJ_5639/이진검색트리_김준우.java
- 알고리즘 종류: 이진 검색 트리
- 알고리즘 개념 간단 설명: 이진 검색 트리는 다음 규칙을 만족한다.
- 노드의 왼쪽 서브트리의 있는 모든 노드의 키는 노드의 키보다 작다
- 노드의 오른쪽 서브트리에 있는 모든 노드의 키는 노드의 키보다 크다
- 이번 문제는 입력값 개수가 주어지지 않아서 iterator를 사용해서 입력을 받았습니다. (hasNext)
- 주어진 전위 순회 결과를 가지고 이진 검색 트리를 구성하고 후위 순회로 결과값을 출력하는 방식으로 코드를 작성해보았습니다.
- maxValue를 사용해서 루트 노드보다 작은 값은 왼쪽 노드에 루트 노드보다 큰 값은 오른쪽 노드에 담기게 해서 이진 검색 트리를 구성했습니다.
- 후위 순회는 가장 많이 사용하는 재귀를 이용해서 순회하도록 했습니다.
- O(n)인거 같습니다
- 코드에 대해서 궁금하신 점이 있다면 언제든 물어봐주세요!
=> 이진검색트리/골드4/50분/X

week05/BOJ_5639/이진검색트리_연예림.java
week 5의 같은 패키지 내에서 준우님과 Node 클래스 명이 같아 발생한 문제 입니다.
확인 후 수정했습니다.
=> fix: duplicate-class

baekjoon-algorithm-study.iml, week06/BOJ_2422/한윤정_김준우.java
- 알고리즘 개념 간단 설명: 모든 가능한 방법을 모두 찾아보는 방법으로 최적화 없이 시도하는 방식으로 매우 효율이 안 좋을 수 있지만, 작은 입력의 경우 시간복잡도는 크지만 확실하게 정답을 찾을 수 있다.
- 먼저 섞어먹으면 안 되는 조합을 boolean[][] 배열을 통해서 표현하였습니다.
- 그리고 삼중 for문을 통해서 모든 가능한 조합을 고려하여 나올 수 있는 조합일 때 count 변수를 1씩 더하는 방식으로 코드를 작성했습니다.
- 여기서 for문을 돌 때 if 문의 조건이 중요했는데, 섞어먹으면 안되는 조합이 나오면 continue를 통해 스킵 하였습니다.
- O(n^3)
- 코드에 대해서 궁금하신 점이 있다면 물어봐 주세요!
=> 한윤정/실버4/40분/X

week06/BOJ_2615/오목_김준우.java
- 격자에서 완전탐색 문제였고, 오목알의 위치를 탐색하기 위해서 dx, dy를 사용하였습니다.
- 이때 방향 8개를 설정하지 않았고, 바둑판을 왼쪽 위에서부터 오른쪽 아래 방향으로 탐색한다는 점을 이용해서 →, ↘, ↓, ↙ 방향으로 이동하도록 설정했습니다.
- for 문을 통해 격자를 이동하면서 바둑알이 존재하면 해당 위치를 기점으로 4방향에 같은 색깔의 바둑알이 위치하는지 파악합니다.
- 만약 다음 위치에 같은 색깔의 바둑알이 위치하면 while 문을 통해서 그 방향으로 계속 이동합니다.
- 바둑알이 5개가 되면 처음 시작한 곳 이전과 이후에  바둑돌이 있는지 확인해 5개가 넘어가는 상황을 체크했습니다.
- 마지막으로 다른 방향은 다 왼쪽 바둑돌을 가리키는데 ↙ 방향이 오른쪽 위를 가리켜서 이 부분은 if 문을 통해서 분류했습니다.
- O(n^3)
- 코드에 대해서 궁금하신 점이 있다면 얘기해주세요!
=> 오목/실버1/45분/X

week06/BOJ_14501/퇴사_김준우.java
- 알고리즘 종류: 재귀를 이용한 완전 탐색
- 재귀를 사용해서 구현을 해보았습니다.
- 만약 퇴사일에 도달하면 최대값을 갱신합니다. 만약 퇴사일을 지나면 종료됩니다.
- n = 1일 때부터 시작하며, n값을 1씩 높인 값도 재귀적으로 확인합니다.
- O(2^n)
- 코드에 대해 궁금하신 점이 있다면 언제든 물어봐주세요!
=> 퇴사/실버3/30분/O

week06/BOJ_2503/숫자야구_이유빈.java
- 알고리즘 종류: 브루트포스
- 가능한 숫자를 모두 확인
- 입력된 숫자와 각 자리수를 비교하며 완전 탐색
O(n)
=> 숫자야구 / 실버3 / 25분 / O

week06/BOJ_2422/한윤정이이탈리아에가서아이스크림을사먹는데_연예림.java
모든 경우의 수를 확인한다.
set과 for문을 사용하여 풀었습니다. N이 200 이하로 제한되어있어 괜찮은 것 같습니다.
```java
// 조합확인
int cnt = 0;
for (int i = 1; i <= n; i++) {
for (int j = i+1; j <= n; j++) {
if (!sets.get(i).contains(j)) {
for (int k = j+1; k <= n; k++) {
if (!sets.get(i).contains(k) && !sets.get(j).contains(k)) {
cnt++;
}
}
}
}
}
```
O(N^2)
=> 한윤정이 이탈리아에 가서 아이스크림을 사먹는데/ 실버4 / 20분 / O

week06/BOJ_2503/숫자야구_연예림.java
완전 탐색인데, 처음에는 어떤 식으로 접근해야할지 생각이 안났습니다
자료를 참고해서 풀었습니다.
1. 가능한 숫자를 모두 확인
2. 입력값과 모두 비교하여 확인
```java
for (int j = 123; j <= 987; j++) {
if (nums[j]) {
int strikeCount = 0;
int ballCount = 0;
for (int k = 0; k < 3; k++) { // 비교하기
String young = String.valueOf(j);
for (int l = 0; l < 3; l++) {
String min = String.valueOf(num);
if(young.charAt(k) == min.charAt(l) && k == l) {
strikeCount++;
}
if(young.charAt(k) == min.charAt(l) && k != l) {
ballCount++;
}
}
}
if (strike != strikeCount || ball != ballCount) {
nums[j] = false;
}
}
}
```
=> 숫자야구 / 실버3 / 30분 / X

week06/BOJ_2615/오목_연예림.java
1.  처음에는 for문을 사용해서 풀었는데, 충분히 탐색하지 않아서 계속 틀렸습니다.
2. 오목판인만큼 탐색할 방향과 크기 제한이 있는 점을 고려해야 할 것 같습니다.
3. 6이상 연결되면 이긴 것이 아니라는 조건을 고려해야 해서 트리로 푸는 게 나을 수 도 있을 것 같습니다.
```java
private static int calc(int x, int y, int dir, int color) { // 재귀로 끝까지 탐색
int nx = x + dx[dir];
int ny = y + dy[dir];
if (map[nx][ny] == color) {
return memo[nx][ny][dir] = calc(nx, ny, dir, color) + 1;
}
return 1;
}
```
다들 어떻게 푸셨나요
=> 오목 / 실버1 / 60분 / X

week06/BOJ_14501/퇴사_연예림.java
- 알고리즘 종류: DP (Dynamic Programming)
- 알고리즘 개념 간단 설명
큰 문제를 작은 문제로 나누어 푸는 것. 
모든 작은 문제들을 한번만 풀어야한다. 이전에 구한 작은 문제의 값을 메해 놓고 사용하는 방식이다. (Memoization)
```java
for (int i = N; i > 0; i--) {
if (times[i] > N - i + 1) {
dp[i] = dp[i+1];
} else {
dp[i] = Math.max(pays[i] + dp[i+times[i]] , dp[i+1]);
// 현재 날짜의 pay + 이후 남은 날짜의 최대 페이 vs 이전 날짜의 최대페이
}
}
```
재귀로 풀려다가 못풀었던 문제입니다. 완전 탐색으로 풀려고 했는데, DP 문제 였네요..
=> 퇴사 / 실버3 / 60분 / X

week06/BOJ_21278/호석이두마리치킨_연예림.java
- 알고리즘 종류:
bfs 탐색과 for 문을 사용하여 풀었습니다.
-  모든 노드에 대한 거리를 구한 후 비교
-  bfs 탐색을 할 때 이미 방문한 노드라도 갱신될 수 있는 값이 작다면 다시 방문합니다.
```java
public static void visit(int start) {
Deque<Integer> deque = new LinkedList<>();
deque.offerLast(start);
check[start][start] = 0;
while (!deque.isEmpty()) {
int n = deque.pollLast();
for (int k : graph.get(n)) {
if ((check[start][k] == 0 && start != k) || check[start][k] > check[start][n] + 2) { // 순환이 있는 경우 고려
check[start][k] = check[start][n] + 2; // 이전값의 + 2를 해서 넣어주기
deque.add(k);
}
}
}
}
```
O(N^2)
=> 호석이두마리치킨 / 골드4 / 70분 / O

week06/BOJ_14501/퇴사_한성지.java
- 알고리즘 종류: 브루트포스 알고리즘
- 알고리즘 개념 간단 설명: 모든 경우를 살펴봄으로써 답을 구하는 알고리즘
1. 각 상담 일수와 이익 저장
2. dp에 i일까지 얻을 수 있는 최대 이익 저장
O(N)
=> 퇴사 / 실버1 / 30분 / X

week06/BOJ_2615/오목_한성지.java
- 알고리즘 종류: 브루트포스 알고리즘 (전체탐색)
오목판에서 현재 바둑돌의 8방향을 검사하여 5개가 연속으로 있는지 확인
O(1)
=> 오목 / 실버1 / 30분 / X

baekjoon-algorithm-study.iml
pull 받고 나니 imi 파일 6주차까지 밖에 없어 다시 수정했습니다~
=> week07 imi 파일 수정 및 폴더 생성

week07/BOJ_11441/출석체크_연예림.java, week07/BOJ_11660/구간합구하기5_연예림.java, week07/BOJ_20438/개똥벌레_연예림.java, week07/BOJ_21318/피아노체조_연예림.java, week07/BOJ_3020/합구하기_연예림.java
=> week07 폴더 및 문제 파일 추가

week07/BOJ_3020/개똥벌레_이유빈.java
- 알고리즘 종류: 누적 합
- 석순일 경우 가로막힌 부분을 만나면 +1을 하고 끝나는 지점에서는 -1을 하여 석순의 길이를 표현한다
- 종유석의 경우 끝나는 지점은 표시할 필요가 없고 가로막힌 부분만 +1을 한다
- 장애물을 만나는 경우를 누적합으로 계산한다
- 누적합의 최소값을 찾고 해당 최소값이 몇번 나오는지 계산한다
O(n)
=> 개똥벌레 / 골드5 / 27분 / O

week06/BOJ_21278/호석이_김준우.java, week07/BOJ_11441/출석체크_연예림.java, week07/BOJ_11441/합구하기_김준우.java, week07/BOJ_11660/구간합구하기5_연예림.java, week07/BOJ_20438/개똥벌레_연예림.java, week07/BOJ_21318/피아노체조_연예림.java, week07/BOJ_3020/합구하기_연예림.java
- 알고리즘 종류: 누적합
- 알고리즘 개념 간단 설명: 누적합은 배열에서 특정 구간의 합을 빠르게 계산하기 위해 미리 합을 저장해 두는 알고리즘 기법!
- 일반적으로 특정 구간의 합을 직접 계산하면 O(N)
- 하지만 누적합을 이용하면 O(1)
- 배열을 통해 입력을 받음과 동시에 누적합을 진행하였습니다.
- O(N)
- 누적합 좋아요
=> 합구하기/실버3/20분/O

week07/BOJ_11441/출석체크_연예림.java, week07/BOJ_11660/구간합구하기5_연예림.java, week07/BOJ_20438/개똥벌레_연예림.java, week07/BOJ_21318/피아노체조_김준우.java, week07/BOJ_21318/피아노체조_연예림.java, week07/BOJ_3020/합구하기_연예림.java
- 알고리즘 종류: 누적합
- 배열에서 이전 값이 이후 값보다 크면 prefix 배열에 1을 더해서 누적합을 시켰습니다.
- O(n)
- 모르겠는 부분이 있다면 물어봐주세요!
=> 피아노체조/실버1/20분/O

week07/BOJ_11441/출석체크_연예림.java, week07/BOJ_11660/구간합구하기5_김준우.java, week07/BOJ_11660/구간합구하기5_연예림.java, week07/BOJ_20438/개똥벌레_연예림.java, week07/BOJ_21318/피아노체조_연예림.java, week07/BOJ_3020/합구하기_연예림.java
- 알고리즘 종류: 2차원에서 부분합
- 2차원에서 부분합 배열을 만드는 것은 괜찮았는데 마지막에 부분 행렬 합을 구하는 부분을 이해하기가 조금 힘들었습니다.
- 먼저 배열은 N + 1 * N + 1 크기로 만들고 i = 0 또는 j = 0 이면 0으로 채웁니다.
- int sum = prefix[x2][y2] - prefix[x1 - 1][y2] - prefix[x2][y1 - 1] + prefix[x1 - 1][y1 - 1]; 이 부분이 이해하기 힘들었습니다.
- 전체 합에서 필요 없는 부분합을 제외한다고 생각하니까 이해가 되었습니다.
- O(n^2)
- 이해가 안되는 부분이 있다면 물어봐주세요
=> 구간합구하기5/실버1/35분/X

week07/BOJ_11441/출석체크_한성지.java
- 알고리즘 종류: 누적합
1. 출석하지 않은 학생을 표시할 student 배열 선언
2. 졸고 있는 학생의 경우 true로 표시
3. 코드를 받은 학생 표시할 code 배열 선언 후, 코드 받은 학생 true 표시
4. 코드를 받지 않은 학생은 student에서 true로 표시
5. student가 ture인 경우 누적합 저장 후 구간합 계산
O(N+K+M)
=> 출석체크 / 실버2 / 30분 / X

week07/BOJ_21318/피아노체조_한성지.java
- 알고리즘 종류: 누적합
실수 횟수의 누적합을 구해서 구간합 계산
O(N+Q)
=> 피아노체조 / 실버1 / 20분 / O

week07/BOJ_20438/개똥벌레_한성지.java
- 알고리즘 종류: 누적합
1. 각 높이의 석순/종유석 개수를 센다.
2. i 이상/이하인 석순/종유석 개수의 누적합을 계산한다.
```java
for (int i = 1; i <= H; i++) {
// 높이 i 이하의 석순 개수 누적합
down[i] += down[i - 1];
}
for (int i = H; i >= 1; i--) {
// 높이 i 이상의 종유석 개수 누적합
up[i] += up[i + 1];
}
```
3. i 이상 석순의 개수 + i 이하 종유석 개수가 가장 작은 구간의 개수를 구한다.
```java
for (int i = 1; i < H + 1; i++) {
// i 이상의 석순 개수 + i 이하의 종유석 개수
int dif = (down[H] - down[i - 1]) + (up[1] - up[i + 1]);
if (dif < min) {
min = dif;
cnt = 1;
} else if (dif == min) {
cnt++;
}
}
```
O(N+H)
=> 개똥벌레 / 골드5 / 30분 / X

week07/BOJ_21318/피아노체조_박유진.java
=> 피아노체조 / 실버1 / 23분 / O

week07/BOJ_11660/구간합구하기5_박유진.java
=> 구간합구하기 / 실버1 / 33분 / O

week07/BOJ_20438/출석체크_박유진.java
=> 출석체크 / 실버2 / 40분 / O

week07/BOJ_11441/합구하기_연예림.java, week07/BOJ_3020/합구하기_연예림.java
- 알고리즘 종류: 구간합
배열 값이 먼저 주어지고 각각 구간합을 구하는 문제라
값의 합을 배열에 저장하는 방식을 사용했습니다.
O(N)
=> 합구하기 / 실버3 / 10분 / O

week07/BOJ_11660/구간합구하기_이유빈.java
- 알고리즘 종류: 누적 합
2차원의 누적 합 array를 만들어서 원하는 영역만큼 계산
O(n^2)
=> 구간합구하기 / 실버1 / 50분 / O

week07/BOJ_11441/합구하기_이유빈.java
- 알고리즘 종류: 누적 합
prefix 배열에 각 위치의 누적합을 계산 후, 실질적으로 어떤 구간의 누적합을 계산할 때는 해당되지 않는 부분까지의 누적합은 제외하는 방식으로 계산한다.
O(n)
=> 합구하기 / 실버3 / 12분 / O

week08/BOJ_2615/오목_김준우_복습.java
- 저번에 탐색하는 방향을 잘못 설정해서 추가적인 코드(가장 왼쪽 바둑알을 찾는 코드)가 필요했었는데, 방향 설정을 올바르게 하니 깔끔하게 코드를 작성할 수 있었습니다
- O(n ^ 2)
- 코드에 대해 궁금하신 점이 있다면 언제든 물어봐주세요
=> :white_check_mark: 오목 / 실버1 / 20분 / O

week08/BOJ_2615/오목_김준우_복습.java, week08/BOJ_3584/가장가까운공통조상_김준우_복습.java
- 알고리즘 종류: 트리
- 알고리즘 개념 간단 설명: 트리는 루트 노드를 제외한 모든 노드가 부모를 가지고 있습니다. 따라서 이번 문제에서는 두 개의 노드가 주어졌을 때 깊이가 가장 깊은 공통의 부모 노드를 찾는 문제였습니다.
- 먼저 부모와 자식 노드의 관계를 저는 Map을 써서 표현했습니다.
- 이때 <Child, Parent> 순서로 담기게 하였는데 이유는 나중에 get() 메서드를 통해서 자식 노드의 부모 노드를 쉽게 찾기 위함입니다.
- 공통의 부모를 찾는 과정은 두 개의 노드가 주어졌을 때 각 노드의 부모 노드를 get()을 통해서 찾고 해당 값을 set에 넣습니다.
- 그리고 다른 노드 또한 부모 노드를 찾으면서 만일 set에 같은 값이 담기게 된다면 해당 값을 리턴합니다
- O(N)
- 코드에 대해서 궁금하신 점이 있다면 언제든 물어봐주세요
=> 가장가까운조상/골드4/30분/O

week08/BOJ_5639/이진검색트리_김준우_복습.java
- 알고리즘 종류: 트리
- 저번 풀이에서는 이진 트리를 만드는 코드를 메서드로 만들어서 풀었었는데, 이번에는 노드 클래스 내에 insert라는 메서드를 만들어서 부모 노드보다 작으면 왼쪽으로 크면 오른쪽으로 삽입하여 트리를 구성하였습니다.
- O(N)
- 코드에 대해서 궁금하신 점이 있다면 언제든 물어봐주세요
=> 이진검색트리/골드4/35분/O

week08/BOJ_21278/호석이두마리치킨_김준우_복습.java
- 이중 배열을 이용해서 두 노드 사이의 거리를 기록했습니다.
- 배열 초기화 시에 본인 노드는 거리를 0으로 설정하고 본인 이외의 노드와의 거리는 INF(가장 큰 값)으로 초기화합니다.
- 그리고 반복문을 통해서 모든 경우의 수를 탐색하며, 특정 노드에서 다른 노드로 갈 때 거리가 최소인 경우를 기록합니다.
- 이제 모든 노드 중에서 2개를 선택해 왕복 거리가 가장 짧은 경우를 완전 탐색을 통해서 찾습니다.
- O(N ^ 3)
=> 호식이두마리치킨/골드4/40분/X

week08/BOJ_16937/두스티커_김준우.java
- 스티커는 회전이 가능하므로 두 스티커를 회전시키면서 가로와 세로로 배치가 가능한지 확인하고, 가능한 경우 최대 넓이를 구하는 코드
- O(N ^ 2)
=> 두스티커/실버3/35분/X

week08/BOJ_3584/가장가까운공통조상_한성지_복습.java
- 알고리즘 종류: 트리
1. 각 자식의 부모 저장
2. 공통 조상을 구할 두 노드 중 하나의 루트까지 가는 길을 표시
3. 나머지 노드가 미리 표시한 노드를 지나면 공통 조상
O(N)
=> 가장가까운공통조상_복습/골드4/30분/X

week08/BOJ_5639/이진검색트리_한성지_복습.java
- 알고리즘 종류: 트리
전위순회를 통해 들어온 입력값을 이용해 트리를 만든 후 후위순회
최악의 경우 O(N^2)
=> 이진검색트리_복습/골드4/30분/X

week08/BOJ_2615/오목_한성지_복습.java
- 알고리즘 종류: 브루트포스 알고리즘
오목돌의 8방향을 모두 검사하여 연속되는 돌이 5개인지 확인
O(1)
=> 오목_복습/실버1/30분/X

week07/BOJ_11441/합구하기_한성지.java, week07/BOJ_20438/출석체크_한성지.java, week07/BOJ_3020/개똥벌레_한성지.java, week08/BOJ_16937/두스티커_한성지.java
- 알고리즘 종류: 브루트포스 알고리즘
1. 모눈종이에 붙일 수 있는 스티커의 정보 저장
2. 스티커 붙이는 모든 경우의 수 검사해서 그 중 가장 큰 넓이 출력
O(N^2)
=> 두스티커/실버3/30분/X

week10/BOJ_1182/부분수열의합_한성지.java, week10/BOJ_14888/연산자끼워넣기_한성지.java, week10/BOJ_16987/계란으로계란치기_한성지.java, week10/BOJ_19699/소난다_한성지.java, week10/BOJ_6443/애너그램_한성지.java
=> week10 문제 파일 및 폴더 추가

week08/BOJ_16937/두스티커_민기.java
- 알고리즘 종류: 부르트포스
**스티커 배치 가능한 경우의 수**
(스티커 1 돌릴지 말지) x (스티커 2 돌릴지 말지) x (두 스티커를 가로로 이어붙일지 세로로 이어붙일지) 해서 최소 8개 가 필요하다
1. 스티커1 그대로, 스티커2 그대로, 가로로 배치
2. 스티커1 그대로, 스티커2 그대로, 세로로 배치
3. 스티커1 그대로, 스티커2 회전, 가로로 배치
4. 스티커1 그대로, 스티커2 회전, 세로로 배치
5. 스티커1 회전, 스티커2 그대로, 가로로 배치
6. 스티커1 회전, 스티커2 그대로, 세로로 배치
7. 스티커1 회전, 스티커2 회전, 가로로 배치
8. 스티커1 회전, 스티커2 회전, 세로로 배치
O(n^2)
=> 두스티커 / 실버3 / 40분 / X

week08/BOJ_2615/오목_박유진_복습.java, week08/BOJ_5639/이진검색트리_박유진_복습.java
=> 오목_복습 / 실버1 / 30분 / X

week08/BOJ_5639/이진검색트리_박유진_복습.java
=> 이진검색트리_복습 / 골4 / 15분 / O

week08/BOJ_3584/가장가까운공통조상_박유진_복습.java
=> 가장가까운공통조상_복습 / 골드4 / 30분 / X

week08/BOJ_16937/두스티커_박유진.java
- 알고리즘 개념 간단 설명: 문제에서 주어지는 변수들의 범위가 크지 않기 때문에 완전 탐색으로 풀 수 있다. 따라서 스티커를 하나씩 다 확인해서 최대 넓이를 계산한다.
중요 포인트
- 두 개의 스티커만 붙일 수 있음. 단, 두 스티커가 겹치면 안된다.
- 스티커는 모눈종이를 벗어나면 안됨
- 스티커를 90도 회전해서 붙일 수 있음
과정
1. 첫 번째로 붙일 스티커 선택하기
2. 두 번째로 붙일 스티커 선택하기
3. 두 스티커들의 넓이를 계산하기
- 만약 이미 저장된 최대 넓이보다 크다면 최대값 갱신
- O(n^2) 예상합니다.
=> 두스티커 / 실버3 / 30분 / X

week08/BOJ_21278/호석이두마리치킨_연예림_복습.java
- 알고리즘 종류: 완전탐색, 너비우선탐색
1. 한 번 탐색한 노드도 cost를 확인하고 재방문을 처리해야 합니다.
- 기존에 풀었던 문제인데, 이번에 다시 풀어도 놓친 조건이 몇 개 있었네요 ㅎㅎ
O(N^2)
=> 호석이두마리치킨_복습 / 골드4 / 40분 / O

week08/BOJ_5639/이진검색트리_연예림_복습.java
- 알고리즘 종류: 이진검색트리
이진 검색 트리 생성 후 다시 탐색하는 문제였습니다.
=> 이진검색트리_복습 / 골드4 / 20분 / O

week08/BOJ_3584/가장가까운공통조상_연예림_복습.java, week08/BOJ_3584/가장가까운조상_연예림_복습.java
- 알고리즘 개념 간단 설명: 노드의 부모를 따라가면 탐색하는 방식
각 노드의 부모를 배열로 기록하고 부모를 따라 올라가 탐색하는 방식을 사용하였습니다.
O(N)
=> 가장가까운조상_복습 / 골드4 / 50분 / O

week08/BOJ_2615/오목_연예림_복습.java
=> 오목_복습 / 실버1 / 60분 / O

week08/BOJ_16937/두스티커_연예림.java
1. 첫 번째 스티커 부착 후 남은 공간과 두 번째 스티커 크기를 비교합니다.
2. 회전 후에도 모눈종이를 벗어나지 않는지 확인하는 조건이 필요합니다.
O(N^2)
=> 두스티커 / 실버3 / 80분 / O

week08/BOJ_16937/두스티커_이유빈.java
- 알고리즘 종류: 브루트포스
- 첫 번째 스티커를 원래대로 붙임
- 첫 번째 스티커를 90도 회전하여 붙임
- 첫 번째 스티커를 붙인 후 남는 공간 게산
- 두 번째 스티커를 원래대로 붙이고 스티커 면적 계산
- 두 번째 스티커를 90도 회전하여 붙이고 스티커 면적 계산
- 가장 최대 면적 구함
O(n^2)
=> 두스티커 / 실버3 / 63분 / X

week10/BOJ_6443/애너그램_한성지.java
1. 단어에 들어있는 알파벳의 개수를 배열에 저장
2. dfs를 이용해 나올 수 있는 모든 애너그램 계산
O(N×P) (P=가능한 에너그램의 수)
=> 애너그램/골드5/30분/X

week10/BOJ_19699/소난다_한성지.java
dfs를 이용해 M마리의 소의 몸무게를 합한 모든 경우의 수 도출
O(2^N)
=> 소난다/실버2/50분/O

week10/BOJ_1182/부분수열의합_한성지.java
dfs를 사용해 공집합에서 정수를 하나씩 더해보며, 해당하는 부분수열의 개수를 구함
O(2^N)
=> 부분수열의합/실버2/30분/X

week10/BOJ_14888/연산자끼워넣기_한성지.java
- 알고리즘 개념 간단 설명: 재귀적으로 문제를 해결하되, 현재 재귀를 통해 확인중인 상태가 제한 조건에 위배되는지 판단하고, 해당 상태가 위배되는 경우 해당 상태를 제외하고 다음 상태로 넘어
깊이 우선 탐색을 통해 모든 경우의 수를 살펴보고, 그 중 최대값과 최소값을 구함
O((N-1)!)
=> 연산자끼워넣기/실버1/30분/X

week10/BOJ_14888/연산자끼워넣기_연예림.java
- 알고리즘 개념 간단 설명
해를 찾아가면서 해를 찾을 수 없는 경로라고 생각되면 되돌아가는 방식이다.
불필요한 경로를 제외하는 “가지치기” 방식이라고 한다. 
```java
// 연산자 개수가 1개 이상인 경우
if (operator[i] > 0) // 연산자가 없는 경우는 제외
```
=> 연산자끼워넣기 / 실버1 / 30분 / X

week10/BOJ_1182/부분수열의합_연예림.java
- 알고리즘 종류: 백트래킹, 재귀
```java
// 현재 값이 목표값과 같으면 cnt++ 하고 리턴
// 또는 현재 인덱스 값이 마지막이면 그냥 리턴 
// -> 초반에는 이렇게 설계했는데, 공집합을 고려하여 아래와 같이 변경하였습니다.
private static void calc_sum(int idx, int sum) {
if (idx == N) {
if (sum == S) {
cnt++;
}
return;
}
calc_sum(idx+1 ,sum); 
calc_sum(idx+1 , sum + nums[idx]); 
}
```
=> 부분수열의합 / 실버2 / 40분 / X

week10/BOJ_19699/소난다_김준우.java
- 알고리즘 종류: DFS를 이용한 완전탐색
- N개의 수에서 M개의 수를 선택하는 방법에는 중첩 for문, DFS, 비트마스킹 등 여러 방법이 있었지만 DFS를 이용한 방법이 가장 직관적인거 같아서 DFS를 이용해 코드를 작성했습니다
- 이번 문제는 N개의 수에서 M개의 수를 선택하고 그들의 합이 소수가 되면 출력하는 문제였습니다.
- DFS는 재귀를 통해 구현하였으며 3개의 수 조합을 만들어서 합이 소수가 되면 Set에 담아 정렬 이후 출력하도록 했습니다
=> 소난다 / 실버2 / 35분 / X

week10/BOJ_6443/애너그램_김준우.java
- 알고리즘 종류: DFS, 백트래킹
- 기저 조건 : depth가 문자열의 길이와 같다면 문자를 전부 선택한 것이므로 완성된 애너그램을 결과에 저장하고 종료합니다
- 반복문을 통해서 배열의 모든 문자를 대상으로 순열을 만들기 위해 순회합니다
- visited 배열을 통해서 이미 쓴 문자는 건너뜁니다
- `if (i > 0 && arr[i] == arr[i - 1] && !visited[i - 1]) continue;` 는 중복 애너그램을 방지하기 위해 사용하였습니다
- 위 조건이 없다면 aab 문자열이 주어질 때 aab가 2번 중복 출력되는 문제가 발생합니다
- 다른 경로에서 문자를 다시 사용할 수 있도록 `visited[i] = false`로 방문 표시를 해제합니다
=> 애너그램 / 골드5 / 35분 / X

week10/BOJ_14888/연산자끼워넣기_김준우.java
- 알고리즘 종류: DFS를 이용한 백트래킹
- 기저 조건 : depth가 N이면 모든 숫자를 다 사용한 경우로 current 결과를 최대값, 최솟값을 비교해서 갱신합니다
- 4개의 연산자 중 개수가 0보다 크면 해당 연산자를 선택한 후 다음 겨로가를 만들고 다음 숫자로 DFS를 진행합니다.
- 한 연산자 사용이 끝나면 다시 개수를 복구합니다
=> 연산자끼워넣기 / 실버1 / 25분 / O

week10/BOJ_19699/소난다_민기.java
- 알고리즘 종류: 백트래킹(Backtracking), 조합(Combination), 소수 판별
1. N마리의 소 중에서 M마리를 선택하는 모든 조합을 백트래킹으로 구합니다.
2. 선택된 소들의 무게 합이 소수인지 확인합니다.
3. 소수인 경우 HashSet에 저장하여 중복을 제거합니다.
4. 결과값들을 정렬한 후 출력합니다 (소수 무게 합이 없으면 -1 출력).
O(2^N)
=> 소난다 / 실버2 / 40분 / X

week10/BOJ_6443/애너그램_민기.java
- 알고리즘 종류: 백트래킹 (Backtracking)
- 알고리즘 개념 간단 설명:  
---
- 입력 문자열을 문자 배열로 변환 후 정렬하여 사전 순으로 순열을 생성합니다.
- `visited[]`로 사용 여부 체크, `prev`로 중복 문자 방지.
- 백트래킹으로 모든 가능한 순열을 만들어 `StringBuilder`에 저장 후 출력합니다.
---
- 시간 복잡도: O(n²)
=> 애너그램/ 골드5 / 50분 / X /

week10/BOJ_1182/부분수열의합_박유진.java
- 알고리즘 개념 간단 설명: 재귀적으로 문제를 해결하되 현재 재귀를 통해 확인 중인 상태가 제한 조건에 위배가 되는지 판단하고, 해당 상태가 위배되는 경우 해당 상태를 제외하고 다음 단계로 넘어간다. 즉, 해를 찾는 도중 해가 절대 될 수 없다고 판단되면, 되돌아가서 다시 해를 찾는 방법이다.
여기서 더 이상 탐색할 필요가 없는 상태를 제외한다는 것을 가지치기라고 한다. 
DFS(Depth-First Search)는 깊이 우선 탐색으로 가능한 모든 경로를 탐색하는데, 불필요할 것 같은 경로를 사전에 차단하지 않기 때문에 경우의 수를 줄이진 못한다. 그렇기 때문에 백트레킹의 가지치기를 통해, 경우의 수를 줄여 해를 찾는다.
- 코멘트로 작성
- O(N!)
=> 부분수열의 합 / 실버2 / 32분 / O

week10/BOJ_19699/소난다_박유진.java
1. 입력된 소의 무게를 모두 더하여 합의 최대값을 먼저 구한다. 
```java
int total = Arrays.stream(cows).sum();
```
2. 구한 최대값 보다 작은 수들 중, 소수인 수를 구한다.
```java
primes = getPrimes(total);
//...
public static Set<Integer> getPrimes(int total){
Set<Integer> primes = new TreeSet<>(); 
for(int i = 2; i <= total; i++) {
boolean isPrimeNumber = true; // 소수 판별을 위한 flag
for(int j = 2; j <= Math.sqrt(i); j++) { // 제곱근을 활용한 소수 판별
if(i%j == 0) { 
isPrimeNumber = false;
break;
}
}
if(isPrimeNumber) {
primes.add(i);
}
}
return primes;
}
```
3. 세마리 소의 무게가 소수인지 판별하여 정답에 추가
``` java
public static void solu(int nowIdx,int cnt, int weight, int[] cows, boolean[] visited){
if(cnt == m){ // m마리의 소를 골랐을 때,
if(primes.contains(weight)){ // 그 소들의 무게 합이 소수라면
answer.add(weight); // 답에 추가
}
return; // 다음 경우는 보지 않아도 되므로, return한다. …
```
=> 소-난다! / 실버1 / 39분 / O

week12/BOJ_1010/다리놓기_민기.java, week12/BOJ_11053/가장긴증가하는부분수열_민기.java, week12/BOJ_2156/포도주시식_민기.java, week12/BOJ_2407/조합_민기.java, week12/BOJ_2839/설탕배달_민기.java
=> DP 폴더 생성 패키지 이름 수정 필요

week10/BOJ_1182/부분수열의합_이유빈.java
- 알고리즘 종류: 백트래
- 부분수열의 합을 계산하는 함수를 작성하되, 현재 원소를 포함할지 안할지를 따로 연산해야 함
```java
dfs(depth+1, sum+arr[depth]);
dfs(depth+1, sum);
```
=> 부분수열의합 / 실버2 / 26분 / O

week10/BOJ_19699/소난다_이유빈.java
- 알고리즘 개념 간단 설명: 재귀적으로 문제를 풀어나가는 방식
- 소수 판별하는 함수 생성
- m개의 합을 구하는 함수 생성
- hastSet에 저장된 결과값을 list로 변환하여 정렬 및 출력
=> 소난다 / 실버2 / 30분 / X

week11/BOJ_2839/설탕배달_김준우.java
- 알고리즘 종류: dp -> 메모이제이션
- dp는 다이내믹 프로그래밍 알고리즘으로 이름만 들으면 어떤 알고리즘인지 모호합니다
- 동적 계획법이라고도 불리는 dp는 큰 문제를 작은 문제로 나누어서 푸는 방식으로 주로 2가지 방식의 문제를 풀 때 효과적입니다
- 겹치는 부분 문제, 최적 부분 구조
- 메모이제이션은 메모리 캐시처럼 한 번 정답을 구하면 자료구조에 메모하는 방식으로 이전 값을 배열에 저장하고 다음 값에서 이전 값이 필요하다면 사용하는 방식입니다.
- 이번 문제는 겹치는 부분 문제로 중요한 부분이 3과 5입니다.
- 만약 설탕의 무게가 5킬로보다 적게 나간다면 3을 최대한 포함도록, 만약 설탕의 무게가 5킬로보다 무겁다면 5를 최대한 포함하도록 코드를 작성해 보았습니다.
<pre>
dp[i] = Math.min(dp[i], dp[i - 3] + 1); 
if (i >= 5) { 
dp[i] = Math.min(dp[i], dp[i - 5] + 1); 
}  </pre>
- O(N)
=> 설탕배달/실버4/20분/O

week13/BOJ_2407/조합_김준우.java
- 알고리즘 종류: dp
- 코드 작성은 빠르게 했으나 dp를 위해 사용한 2차원 배열에서 입력값 범위를 담지 못해서 계속해서 실패했습니다.
- 자료형 BigInteger를 통해서 해결했습니다.
O(n^2)
=> 조합 / 실버3 / 15분 / O

week13/BOJ_2156/포도주시식_김준우.java
- 알고리즘 종류: 점화식을 이용한 dp 알고리즘
- 이번 문제에서 중요한 부분은 3개의 잔을 연속적으로 마실 수 없다는 점입니다
- 그렇다면 3가지 경우의 수가 나올 수 있습니다
- 이번 잔을 마시지 않는다
- 이전 잔을 마시지 않고 이번 잔을 마신다
- 이전 잔을 마시고 이번 잔도 마신다.
해당 3가지 경우의 수 중에 가장 큰 경우의 수를 dp에 저장하도록 했습니다.
O(n)
=> 포도주시식 / 실버1 / 40분 / X

week13/BOJ_1010/다리놓기_김준우.java
- 알고리즘 종류: dp 알고리즘
- 알고리즘 개념 간단 설명: 하나의 큰 문제를 작은 문제로 나누어 풀기
- 다리 놓기 문제는 옛날에 확률과 통계 공부할 때 조합을 사용해서 풀었던 기억이 있어서 조합을 이용해서 해결했습니다
- 조합은 파스칼의 삼각형에 따라서 dp 알고리즘을 사용해서 표현할 수 있습니다.
- nCr = n-1Cr-1 + n-1Cr
- 문제에서 최대 입력값이 30인 것을 이용해서 30까지의 조합을 이차원 배열을 통해서 미리 구했습니다.
- O(n^2)
=> 다리놓기/실버5/25분/O

week14/BOJ_11727/_2xn타일링2_박유진.java, week14/BOJ_21921/블로그_박유진.java, week14/BOJ_22857/가장긴짝수연속한부분수열S_박유진.java, week14/BOJ_22862/가장긴짝수연속한부분수열L_박유진.java, week14/BOJ_9251/LCS_박유진.java
=> week14 문제 폴더 및 파일 추가

week13/BOJ_11053/가장긴증가하는부분수열_박유진.java
- 알고리즘 종류: dp
가장 긴 증가하는 부분 수열(Longest Increasing Subsequence, LIS)을 찾는 DP 알고리즘
각 위치(i)까지의 최장 증가 부분 수열 길이를 저장하면서 진행
매 원소마다 이전의 모든 원소들을 검사하여, 현재 원소보다 작은 값들 중에서 가장 긴 LIS에 현재 원소를 추가하는 방식
최종적으로 배열 dp에서 가장 큰 값이 전체 수열의 LIS 길이가 된다. 
```java
// dp[i]: i번째 원소를 마지막으로 하는 최장 증가 부분 수열의 길이
int[] dp = new int[n];
```
```java
// 모든 원소에 대해 LIS 계산
for(int i = 0; i < n; i++) {
// 자기 자신만으로 이루어진 부분 수열의 길이는 최소 1
dp[i] = 1;
// 현재(i)보다 이전에 있는 원소들을 모두 검사
for(int j = 0; j < i; j++) {
// 조건 1: 이전 원소가 현재 원소보다 작아야 함 (증가하는 수열 조건)
// 조건 2: i번째 dp값이 j번째 dp+1 값보다 작은 경우 (더 긴 증가 수열 발견)
if (arr[j] < arr[i] && dp[i] < dp[j] + 1) {
// i번째 원소를 마지막으로 하는 LIS 길이 갱신
dp[i] = dp[j] + 1;
}
}
}
```
```java
// 모든 dp값 중 최대값(=가장 긴 증가하는 부분 수열의 길이) 찾기
int max = -1;
for(int i = 0; i < n; i++) {
max = Math.max(dp[i], …
```
=> 가장긴증가하는부분수열 / 실버2 / 30분 / X

week13/BOJ_2407/조합_박유진.java
- 알고리즘 종류: DP
동적 프로그래밍(Dynamic Programming, DP)은 복잡한 문제를 더 작고 간단한 하위 문제로 나누어 해결하는 알고리즘 기법이다.  그리디 알고리즘으로 해결할 수 없는 최적화 문제나 재귀로 해결 시 지수적 시간 복잡도를 가지는 문제를 효율적으로 해결할 수 있게 해주는 기법이다.
[주요 특징]
- 중복 계산 방지: 동일한 하위 문제의 결과를 저장(메모이제이션)하여 재계산을 피함
- 최적 부분 구조: 큰 문제의 최적 해결책이 하위 문제들의 최적 해결책으로부터 구성되는 특성
[접근 방식]
- 상향식(Bottom-up): 작은 문제부터 해결하여 큰 문제로 확장하는 방식
- 하향식(Top-down): 큰 문제에서 시작하여 재귀적으로 작은 문제를 해결하는 방식
[대표적인 문제 유형]
- 피보나치 수열
- 최단 경로 문제
- 배낭 문제(Knapsack)
- 최장 공통 부분 수열(LCS)
- 편집 거리(Edit Distance)
- ~~O(n^2)~~ 
- O(n × r) : 메모이제이션이 없다면 시간 복잡도는 O(2^n)까지 증가할 수 있지만, 메모이제이션 덕분에 효율적인 계산이 가능하다.
=> 조합 / 실버3 / 30분 / X

week13/BOJ_1010/다리놓기_박유진.java
- 알고리즘 종류: DP
- 알고리즘 개념 간단 설명: DP를 이용한 조합.
조합값은 파스칼의 삼각형 성질을 가짐을 이용한 문제.
```java
// DP 테이블 선언 - 조합 계산을 위한 배열 (nCr 계산용)
int dp[][] = new int[30][30];
// 조합의 성질에 따라 초기값 설정: nC0 = 1, nCn = 1
for(int i=0; i<30; i++) {
dp[i][0] = 1;  // nC0 = 1
dp[i][i] = 1;  // nCn = 1
}
```
```java
// 파스칼의 삼각형 성질을 이용하여 조합값 계산
// nCr = (n-1)C(r-1) + (n-1)Cr
for(int i=1; i<30; i++) {
for(int j=1; j<=i; j++) {
dp[i][j] = dp[i-1][j-1] + dp[i-1][j];
}
}
```
```java
// 테스트 케이스 수만큼 반복
while(T-->0) {
// 공백으로 구분된 N, M 입력받기
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());  // 서쪽 사이트 수
int M = Integer.parseInt(st.nextToken());  // 동쪽 사이트 수
// M개 중에서 N개를 선택하는 조합의 수 출력 (MCN)
System.out.println(dp[M][N]);
}
```
- O(1)... 
- DP 테이블을 채우는 데 30×30 연산이 필요하지만, 이는 상수 시간에 해당
=> 다리놓기 / 실버5 / 30분 / X

week13/BOJ_2407/조합_한성지.java
- 알고리즘 종류: 동적 계획법
- 매우 큰 수를 다루기 위해 `BigInteger` 클래스 사용
- dp와 조합의 성질 이용
O(n*m)
=> 조합 / 실버3 / 20분 / O

week13/BOJ_11053/가장긴증가하는부분수열_민기.java
- 알고리즘 종류: DP, 최장 증가 부분 수열
1. `arr[i]`는 수열의 i번째 값을 의미하고, `dp[i]`는 i번째 값을 끝으로 하는 가장 긴 증가 부분 수열의 길이.
2. `top(i)` 함수는 i번째 값 이전의 수 중에서 자기보다 작은 값을 찾아, 그 인덱스까지의 LIS 값에 +1을 하여 최댓값을 구한다.
3. 메인에서 전체 인덱스에 대해 `top(i)` 값을 돌리면서 최댓값을 추출하여 전체 수열의 LIS 길이를 구한다.
4. 중복 계산을 피하기 위해 이미 계산한 `dp[i]` 값은 메모이제이션을 통해 넘어간다.
- O(N²)
=> 가장긴증가하는부분수열/실버2/50분/X

week13/BOJ_2839/설탕배달_민기.java
- 알고리즘 종류: 다이나믹 프로그래밍(DP), 메모이제이션, 재귀
1. `memo[N]` 배열을 -1로 초기화하여 방문 여부 체크 및 결과 저장에 활용합니다.
2. 재귀적으로 `N-3`, `N-5`를 호출하면서 최소 봉지 수를 계산합니다.
3. 기저 조건:
- N == 0 → 정확히 나누어 떨어진 경우 → 0 반환
- N < 0 → 나누어 떨어지지 않는 경우 → 매우 큰 값 반환
4. 최소 봉지 수를 구해야 하므로 `Math.min(from3 + 1, from5 + 1)`을 이용해 현재 봉지도 포함시킵니다.
5. 결과가 `max` 이상이면 정확히 나눌 수 없는 경우이므로 `-1` 출력.
- 재귀 호출은 메모이제이션으로 인해 각 N에 대해 한 번만 수행 → O(N)
- 처음에는 문제에서 정확히 나눌 수 없는 경우(-1 출력)를 처리하지 않아 예외 상황인지 확인이 오래 걸렸습니다.
- 재귀 함수에서 봉지 개수를 왜 `+1` 해야 하는지 개념적으로 직관이 잘 안 되어 구현에 오래 걸렸습니다.
=> 설탕배달/실버4/40분/X

week13/BOJ_2407/조합_민기.java
- 알고리즘 종류: 다이나믹 프로그래밍(DP) Top-Down방식
1. `BigInteger` 타입을 이용해 2차원 배열 `dp[n][r]`에 조합 값을 저장.
2. 기저 조건인 n == r 또는 r == 0일 경우 `1`을 반환.
3. 이미 계산한 값은 `dp[n][r]`에서 가져오고, 아니라면 재귀적으로 계산하여 저장.
4. 입력으로 주어진 `n`, `r`에 대해 `combination(n, r)` 결과를 출력.
- 총 시간 복잡도: O(n*r)
- 일반적인 조합 문제와는 달리, 입력 수가 매우 커지는 경우(long 타입도 초과) 때문에 백준에서 계속 틀려 `BigInteger`를 사용했습니다.
=> 조합/실버3/20분/O

week13/BOJ_1010/다리놓기_민기.java
- 알고리즘 종류: 다이나믹 프로그래밍(DP), 파스칼의 삼각형
1. 최대 입력 범위에 맞춰 2차원 dp 배열(dp[30][30])을 생성합니다.  ( Bottom Up형식으로 문제 풀이를 위해)
2. 파스칼의 삼각형의 기본 성질을 이용해, n == r 또는 r == 0일 때 dp[n][r] = 1로 초기화합니다.
3. dp[i][j] = dp[i-1][j-1] + dp[i-1][j] 를 이용하여 조합 값을 미리 계산해둡니다.
4. 테스트 케이스마다 M과 N을 입력받고, dp[M][N]을 정답으로 출력합니다. (M개 중 N개 선택)
- 총 시간 복잡도: O(N²)
=> 다리놓기/실버5/30분/X

week14/BOJ_22862/가장긴짝수연속한부분수열L_민기.java
- **투 포인터 (Two Pointer)**
- 두 개의 포인터(`left`, `right`)를 사용해 연속한 구간을 탐색하면서 조건을 만족하는 최대 구간 길이를 구하는 방식입니다.  
- 이 문제에서는 홀수를 최대 `K`개까지 제거하고, 남은 짝수의 연속 부분 수열 중 가장 긴 것을 찾습니다.
---
- 수열에서 두 포인터를 이동시키며 홀수 개수를 세고, `K`개를 초과할 경우 `left` 포인터를 이동시켜 조건을 만족하도록 조정합니다.
- 조건을 만족하는 구간의 길이에서 홀수 개수를 빼서 **짝수의 최대 연속 길이**를 계산합니다.
- 그 값을 `max_len`에 저장하며 최댓값을 계속 갱신합니다.
---
- **O(N)**  
- 포인터가 전체 배열을 한 번씩만 순회하므로 선형 시간 복잡도입니다.
---
=> 가장긴짝수연속한부분수열L/골드5/40분/O

week15/BOJ_2805/나무자르기_민기.java
- **알고리즘 종류**: 이분 탐색 (Binary Search)
- **간단 설명**: 절단기 높이를 기준으로 이분 탐색을 진행하여 조건(M 이상 얻는 나무 길이)을 만족하는 최대 높이를 찾는 문제입니다.
- 입력받은 나무 길이를 정렬합니다.
- 절단기 높이 범위(`low = 0`, `high = 최대 나무 길이`)를 정해 이분 탐색을 수행합니다.
- 각 `mid` 높이에 대해 잘려 나오는 총 나무 길이를 계산합니다.
- `sum >= M`이면 조건을 만족하므로 절단기 높이를 더 높여 시도하고, 아니라면 낮춥니다.
- 최종적으로 가능한 절단기 높이의 최대값을 출력합니다.
---
- **O(N log H)**  
- N: 나무의 수  
- H: 나무 높이의 최대값 (범위에서 이분 탐색)
---
=> 나무자르기_민기/실버2/30분/O

week13/BOJ_1010/다리놓기_박유진.java, week14/BOJ_21921/블로그_한성지.java
- 알고리즘 종류: 슬라이딩 윈도우
- 알고리즘 개념 간단 설명: 2개의 포인터로 범위를 지정한 다음, 범위를 유지한 채로 이동하며 문제를 해결하는 방식
```java
for (int i = X; i < N; i++) {
sum = sum - visitorCounts[i-X] + visitorCounts[i];
}
```
- 첫 구간을 더해놓은 뒤, 다음 구간으로 옮기면서 i-X 인덱스 부분을 빼고 i를 더하여, 다음 구간의 합을 구함
O(N)
=> 블로그 / 실버3 / 30분 / X

week15/BOJ_2512/예산_박유진.java
=> 예산 / 실버2 / 30분 / X

baekjoon-algorithm-study.iml, week17/BOJ_11403/경로찾기_이유빈.java
- 알고리즘 종류: 플로이드 와샬
- 알고리즘 개념 간단 설명: 모든 정점에서 모든 정점으로의 최단 거리를 구하는 알고리즘
임의의 중점 k를 두고 l - k의 경로가 있고, k - m의 경로가 있으면 l - m의 경로가 존재함
O(n³)
=> 경로찾기 / 실버1 / 38분 / O

baekjoon-algorithm-study.iml, week16/BOJ_1238/파티_박유진.java, week17/BOJ_11404/플로이드_박유진.java, week18/BOJ_1219/오민식의고민_박유진.java
=> 최단거리알고리즘 박유진

baekjoon-algorithm-study.iml, week16/BOJ_4485/녹색옷입은애가젤다지_민기.java, week17/BOJ_11403/경로찾기_이유빈.java, week19/BOJ_1717/집합의표현_박유진.java
=> 집합의표현 / 골드4 / 30분 / X

week14/BOJ_22857/가장긴짝수연속한부분수열S_김준우.java
- 알고리즘 종류: 투포인터
- 알고리즘 개념 간단 설명: 투포인터는 리스트에 순차적으로 접근 시 두 개의 점의 위치를 기록하면서 처리하는 알고리즘입니다.
- left, right 이라는 변수를 이용해서 투포인트 기법을 사용하였습니다.
- 배열에서 K개의 수를 제외할 수 있으며 이때 최대의 연속하는 짝수들의 길이를 구하는 것이 문제였습니다.
- 따라서 right 포인터가 먼저 이동하면서 만약 배열의 값이 홀수이면 oddCount를 증가시킵니다.
- 만약 홀수의 개수가 K개를 넘어갔다면 왼쪽 포인터를 홀수의 개수가 K개 이내가 될 때까지 이동시킵니다.
- 연속하는 짝수의 최대 개수는 `전체 개수 - 홀수 개수` 입니다.
- O(n^2)
=> 가장긴짝수연속한부분수열/실버2/30분/X

baekjoon-algorithm-study.iml, re01/BOJ_1012/유기농배추_김준우.java
- 알고리즘 종류: DFS
- 그래프의 연결성을 확인하고 개수를 세어보는 문제였습니다
- 해당 문제를 보고 그래프 탐색이고 DFS를 바로 떠올렸으나 격자 탐색에서 DFS를 적용하는 방법을 제대로 구현하지 못했습니다
- DFS 탐색 코드를 보면 재귀를 통해 구현했습니다
- DFS를 통해 연결된 격자를 탐색합니다 visited[x][y] = true로 바뀌게 됩니다
- 따라서 서로 연결된 격자들의 개수를 구할 수 있습니다
입력값 T, M, N에 따라 O(T * M * N)의 시간복잡도가 예상됩니다
- 노션 : https://shimmering-drifter-eef.notion.site/1012-24e5046d9f3c807db913ce29c0f37080?pvs=74
=> 유기농배추/실버2/35분/X

baekjoon-algorithm-study.iml, re01/BOJ_2606/바이러스_박유진.java
- 알고리즘 종류: DFS/BFS - BFS 선택
그래프 탐색 알고리즘 중 하나로, 한 노드에서 출발하여 인접한 노드를 모두 탐색(너비 우선)한 후에 다음 노드를 탐색하는 알고리즘이다.
그에 반해 DFS(깊이 우선 탐색)는 한 노드에서 출발하여 연결된 노드들을 끝까지 탐색(깊이 우선)하는 알고리즘이다. 
이와 같이 노드의 수가 많지 않은 문제는 두 방법 모두 사용할 수 있으나, 노드의 수가 매우 많아지면 DFS의 경우 탐색하지 않아도 되는 경로도 탐색하는 경우가 있기 때문에 유의하여야한다.
```java
ArrayList<ArrayList<Integer>> list = new ArrayList<>(); // 인접리스트 생성
int[] visited = new int[n]; // 노드 방문 여부 
for (int i = 0 ; i < n ; i++){
list.add(new ArrayList<>()); // 인접 리스트 초기화
}
for(int i = 0; i < v; i++){
int a = Integer.parseInt(st.nextToken());
int b = Integer.parseInt(st.nextToken());
list.get(a-1).add(b-1); // 인접 리스트 연결
list.get(b-1).add(a-1); 
}
int answer = 0; // 감염된 PC 수
Queue<Integer> q = new LinkedList<>(); // 방문할 노드 저장
q.add(0); // …
```
=> 바이러스 / 실버3 / 50분 / X

baekjoon-algorithm-study.iml, re01/BOJ_1012/유기농배추_연예림.java, re01/BOJ_2606/바이러스_연예림.java
- 알고리즘 종류: BFS 
- 알고리즘 설명: [그래프 탐색: BFS와 DFS](https://harvest-typhoon-397.notion.site/24db0d5bc00b807b9f77c49a02946df6?pvs=74)
1. 연결 정보를 리스트에 저장
2. 1번 출발점을 시작으로 BFS 탐색
-  노드 수가 최대 100 이하
- 노드 당 1번, 링크당 2번 -> `O(V+E)`
https://harvest-typhoon-397.notion.site/2606-24db0d5bc00b80a3b633ffaf690b140e?pvs=74
=> 바이러스 / 실버3 / 30분 / O

baekjoon-algorithm-study.iml, re02/BOJ_2667/단지번호붙이기_김준우.java
- 알고리즘 종류: 그래프 탐색 (DFS)
- 알고리즘 노션 정리 : https://shimmering-drifter-eef.notion.site/24c5046d9f3c80edbad1eec9f54698db?pvs=74
- 깊이 우선 탐색을 통해 그래프 연결성을 파악하는 문제였습니다
- 문제 풀이 : https://shimmering-drifter-eef.notion.site/2667-2555046d9f3c80f698b0c96f07132696
- O(N ^ 2)
=> 단지번호붙이기/실버1/20분/O

re02/BOJ_2468/안전영역_박유진.java
- 알고리즘 종류: DFS
- 알고리즘 개념 간단 설명: 깊이 우선 탐색 알고리즘으로 연결되어있는 노드들을 리프까지 탐색해나가는 알고리즘이다.
```java
static int n;
static int[][] areas = new int[101][101]; //지역별 수위를 저장할 배열
static boolean[][] visited;   // 방문 여부를 저장할 배열 -> 매 수위마다 초기화한다.
static int answer = 1; // 안전한 영역의 최대 값(결과)가 들어갈 곳
static int maxLevel = 0;  // 가능한 최대 수위
static int minLevel = 101; //가능한 최소 수위
```
```java
for(int i=0; i<n ; i++){
for(int j = 0; j < n; j++ ){
areas[i][j] = Integer.parseInt(st.nextToken());
// 반복문 횟수를 줄이기 위해 가능한 수위 범위를 저장한다.
maxLevel = Math.max(maxLevel, areas[i][j]); // 최대 수위
minLevel = Math.min(minLevel, areas[i][j]); // 최소 수위
}
```
```java
// 입력받으면서 구한 최대 수위와 최소 수위에서만 검사한다.
// 매 수위마다 잠기지 않는 영역의 수를 구한다.
for(int h = minLevel; h< maxLevel; h++){ 
visited = new …
```
=> 안전영역 / 실버1 / 32분 / O

re02/BOJ_20006/랭킹전대기열_연예림.java
- 알고리즘 종류: 구현
- 풀이: [20006 - 랭킹전 대기열 풀이](https://harvest-typhoon-397.notion.site/20006-257b0d5bc00b807e9cade6baa8394803)
- 게임 방에서 멤버 정원을 관리하는 단순 구현 문제입니다.
- 정원 (M)이 1인 경우를 놓쳤었습니다. 
- 방에 멤버 추가 전이 아닌 후에 `isFull()` 검사를 하고, 정원이 차지 않은 방을 별도의 List로 관리했었는데, 오히려 복잡도가 올라가 삭제하였습니다.
- 입력 값이 300 이 최대라 정원이 차지 않은 방을 따로 고려하지 않고 전체 탐색해도 괜찮은 것 같습니다.
O(PxM)
=> 랭킹전대기열/실버2/60분/X

re03/BOJ_1043_김준우.java
- 알고리즘 종류: Union - Find
- 알고리즘 개념 간단 설명:
개념 : [유니온파인드 개념](https://shimmering-drifter-eef.notion.site/Union-Find-25e5046d9f3c80f0a3eff89382fe069c?pvs=74)
문제 풀이 : [1043 문제 풀이](https://shimmering-drifter-eef.notion.site/1043-25e5046d9f3c80168bd9d34e41f0a71f?pvs=74)
O(m * P)
- m은 파티 수, p는 파티에 따른 참여 인원의 총 합
추가 문제 1717 풀이 : [1717 문제 풀이](https://shimmering-drifter-eef.notion.site/1717-25e5046d9f3c801c991ffeb4d40b4d35?pvs=74)
=> 거짓말/골드4/50분/X

re03/BOJ_1541/잃어버린괄호_연예림.java
- 알고리즘 종류: 구현
- 풀이: [1541 - 잃어버린 괄호](https://harvest-typhoon-397.notion.site/1541-25cb0d5bc00b806fb88fcaffede074a8?source=copy_link)
O(N)
=> 잃어버린괄호/실버2/12분/O

re03/BOJ_1011/flyme_박유진.java
- 알고리즘 종류: 수학
- 풀이: https://www.notion.so/1011-25aa788b97e080ff90c8d409834c9e40?source=copy_link
- O(n)
=> Flyme / 골드5 / 47분 / X

re04/BOJ_7569/토마토_박유진.java
- 알고리즘 종류: BFS
- 알고리즘 개념 간단 설명: 너비우선 탐색
```java
tomatos = new int[h][n][m]; // 토마토 상자 정보가 저장될 배열
Queue<Tomato> q = new LinkedList<>(); // 익은 토마토가 들어갈 큐
for(int i=0; i<h; i++){
for(int j=0; j<n; j++){
for(int k = 0; k<m; k++){
tomatos[i][j][k] = Integer.parseInt(st.nextToken()); 
if(tomatos[i][j][k] == 1){ // 1이라면 익은 토마토
q.add(new Tomato(i, j, k));
}
}
}
}
```
```java
static int m, n, h;
static int[][][] tomatos;
// 3차원, 방향이 상하좌우 뿐만 아니라 위 아래 포함하여 6개
static int dy[] = {1, 0, -1, 0, 0, 0}; 
static int dx[] = {0, 1, 0, -1, 0, 0};
static int dz[] = {0, 0, 0, 0, 1, -1};
// 아직 익지 않은 토마토가 있는 곳인지 검사하는 함수
static boolean check(int nz, int ny, int nx, int[][][] tomatos){
if(nz < 0 || ny < 0  || nx < 0 || nz >= h || ny >= n || nx >= m ) return false; // 범위 밖 …
```
=> 토마토 / 골드5 / 60분 / X
